Repository octobercms/october, pull requests merged in 2018-10, with the labels that each got.

#3834 fix css: 'width' style in backend columns.yaml won't work when use c…
  modules/system/assets/css/styles.css
  modules/system/assets/ui/less/site.normalize.less
  modules/system/assets/ui/storm.css
Labels: Type: Maintenance

#3841 Fix CloudFlare breaking the backend
  modules/backend/layouts/_head.htm
  modules/backend/layouts/auth.htm
Labels: Type: Maintenance

#3838 Change z-index of full-screen mode of markdown editor
  modules/backend/formwidgets/markdowneditor/assets/less/markdowneditor.less
Labels: Status: Completed, Type: Maintenance

#3840 Revert of 'loader.less', based on the issue #3792
  modules/system/assets/ui/less/loader.less
  modules/system/assets/ui/storm.css
Labels: Type: Maintenance

#3848 Fixed scoreboard label in mail partial update view
  modules/system/controllers/mailpartials/update.htm
Labels: Type: Maintenance

#3847 Allow plugins to register their own mail partials
  modules/system/classes/MailManager.php
  modules/system/classes/PluginBase.php
Labels: Status: Review Needed, Type: Maintenance

#3850 Added registerMailLayouts method to PluginBase
  modules/system/classes/MailManager.php
  modules/system/classes/PluginBase.php
Labels: Status: In Progress, Type: Maintenance

#3852 Change the delete buttons style to danger
  modules/cms/controllers/index/_content_toolbar.htm
  modules/cms/controllers/index/_layout_toolbar.htm
  modules/cms/controllers/index/_page_toolbar.htm
  modules/cms/controllers/index/_partial_toolbar.htm
  modules/cms/controllers/themelogs/_list_toolbar.htm
  modules/cms/widgets/templatelist/partials/_toolbar.htm
  modules/system/controllers/eventlogs/_list_toolbar.htm
  modules/system/controllers/requestlogs/_list_toolbar.htm
Labels: Type: Maintenance

#3853 Check that getProperties method returns an array
  modules/cms/classes/ComponentHelpers.php
Labels: Type: Maintenance

#3857 CodeEditor 'ctrl + f' dirty issue
  modules/system/assets/ui/js/input.monitor.js
  modules/system/assets/ui/storm-min.js
Labels: Type: Maintenance

#3860 Added more inline documentation for events
  modules/cms/classes/Controller.php
  modules/cms/classes/Router.php
  modules/cms/classes/Theme.php
  modules/cms/controllers/Index.php
  modules/cms/twig/Loader.php
Labels: Type: Maintenance

#3865 Add last modified date to Pages, Partials, Layouts and Content
  modules/cms/controllers/Index.php
  modules/cms/controllers/index/_content_toolbar.htm
  modules/cms/controllers/index/_layout_toolbar.htm
  modules/cms/controllers/index/_page_toolbar.htm
  modules/cms/controllers/index/_partial_toolbar.htm
Labels: Status: Completed, Type: Maintenance

#3815 Add filters to log pages
  modules/backend/controllers/accesslogs/config_filter.yaml
  modules/backend/controllers/accesslogs/config_list.yaml
  modules/backend/lang/en/lang.php
  modules/backend/lang/hu/lang.php
  modules/backend/models/accesslog/columns.yaml
  modules/cms/controllers/themelogs/config_filter.yaml
  modules/cms/controllers/themelogs/config_list.yaml
  modules/system/controllers/eventlogs/config_filter.yaml
  modules/system/controllers/eventlogs/config_list.yaml
Labels: Status: Completed, Type: Enhancement

#3869 Improve linking from ActiveTheme report widget with permissions
  modules/cms/reportwidgets/ActiveTheme.php
  modules/cms/reportwidgets/activetheme/partials/_widget.htm
Labels: Type: Maintenance

#3881 Update lang.php
  modules/system/lang/sk/lang.php
Labels: Type: Maintenance

#3885 PR for Date Modifed
  modules/cms/controllers/index/_content_toolbar.htm
  modules/cms/controllers/index/_layout_toolbar.htm
  modules/cms/controllers/index/_page_toolbar.htm
  modules/cms/controllers/index/_partial_toolbar.htm
Labels: Status: Completed, Type: Maintenance

#3891 Fix positioning for popovers
  modules/system/assets/ui/js/popover.js
Labels: Type: Maintenance

#3895 Update Ducth (NL) translation
  modules/backend/lang/nl/lang.php
  modules/cms/lang/nl/lang.php
  modules/system/assets/js/lang/lang.nl.js
  modules/system/lang/en/client.php
  modules/system/lang/nl/client.php
  modules/system/lang/nl/lang.php
  modules/system/lang/nl/validation.php
Labels: Type: Maintenance

#3882 Add Filter Buttons
  modules/system/assets/ui/js/filter.dates.js
  modules/system/assets/ui/js/filter.js
  modules/system/lang/en/client.php
Labels: Status: Completed, Type: Enhancement

#3886 Update October CMS from jQuery V2 to V3.3.1 and add JQuery Migrate
  modules/backend/assets/js/october.alert.js
  modules/backend/assets/js/october.flyout.js
  modules/backend/assets/js/october.navbar.js
  modules/backend/assets/js/october.sidepaneltab.js
  modules/backend/assets/js/vendor/jquery-migrate.min.js
  modules/backend/assets/js/vendor/jquery.min.js
  modules/backend/layouts/_head.htm
  modules/backend/layouts/auth.htm
  modules/system/assets/ui/vendor/pikaday/README.md
  modules/system/classes/CombineAssets.php
  modules/system/controllers/mailbrandsettings/_field_mail_preview.htm
Labels: Status: Completed, Type: Maintenance

#3888 [UX] Tab Icons
  modules/backend/classes/FormTabs.php
  modules/backend/widgets/form/partials/_form_tabs.htm
  modules/system/assets/ui/less/tab.less
Labels: Status: Revision Needed, Type: Enhancement

#3901 Add Tab icons functionality
  modules/backend/assets/js/october-min.js
  modules/backend/classes/FormTabs.php
  modules/backend/models/user/fields.yaml
  modules/backend/widgets/form/partials/_form_tabs.htm
  modules/system/assets/js/lang/lang.ar.js
  modules/system/assets/js/lang/lang.be.js
  modules/system/assets/js/lang/lang.bg.js
  modules/system/assets/js/lang/lang.ca.js
  modules/system/assets/js/lang/lang.cs.js
  modules/system/assets/js/lang/lang.da.js
  modules/system/assets/js/lang/lang.de.js
  modules/system/assets/js/lang/lang.el.js
  modules/system/assets/js/lang/lang.en-au.js
  modules/system/assets/js/lang/lang.en-ca.js
  modules/system/assets/js/lang/lang.en-gb.js
  modules/system/assets/js/lang/lang.en.js
  modules/system/assets/js/lang/lang.es-ar.js
  modules/system/assets/js/lang/lang.es.js
  modules/system/assets/js/lang/lang.et.js
  modules/system/assets/js/lang/lang.fa.js
  modules/system/assets/js/lang/lang.fi.js
  modules/system/assets/js/lang/lang.fr-ca.js
  modules/system/assets/js/lang/lang.fr.js
  modules/system/assets/js/lang/lang.hu.js
  modules/system/assets/js/lang/lang.id.js
  modules/system/assets/js/lang/lang.it.js
  modules/system/assets/js/lang/lang.ja.js
  modules/system/assets/js/lang/lang.kr.js
  modules/system/assets/js/lang/lang.lt.js
  modules/system/assets/js/lang/lang.lv.js
  modules/system/assets/js/lang/lang.nb-no.js
  modules/system/assets/js/lang/lang.nl.js
  modules/system/assets/js/lang/lang.pl.js
  modules/system/assets/js/lang/lang.pt-br.js
  modules/system/assets/js/lang/lang.pt-pt.js
  modules/system/assets/js/lang/lang.ro.js
  modules/system/assets/js/lang/lang.ru.js
  modules/system/assets/js/lang/lang.sk.js
  modules/system/assets/js/lang/lang.sv.js
  modules/system/assets/js/lang/lang.tr.js
  modules/system/assets/js/lang/lang.uk.js
  modules/system/assets/js/lang/lang.vn.js
  modules/system/assets/js/lang/lang.zh-cn.js
  modules/system/assets/js/lang/lang.zh-tw.js
  modules/system/assets/ui/less/tab.less
  modules/system/assets/ui/storm.css
Labels: Status: Completed, Type: Enhancement
