Repository octobercms/october, pull requests merged in 2018-08, with the labels that each got.

#3671 Add Slovak language
  modules/backend/lang/sk/lang.php
  modules/cms/lang/sk/lang.php
  modules/system/lang/sk/client.php
  modules/system/lang/sk/lang.php
  modules/system/lang/sk/validation.php
Labels: Status: Completed, Type: Enhancement

#3670 Passing parameters as an array
  modules/backend/widgets/Form.php
Labels: Status: Revision Needed, Type: Maintenance

#3682 Check if exists the missing dependency
  modules/system/classes/PluginManager.php
Labels: Type: Maintenance

#3687 Add customization of froala lineBreaker tags
  modules/backend/formwidgets/RichEditor.php
  modules/backend/formwidgets/richeditor/assets/js/build-min.js
  modules/backend/formwidgets/richeditor/assets/js/richeditor.js
  modules/backend/formwidgets/richeditor/partials/_richeditor.htm
  modules/backend/lang/en/lang.php
  modules/backend/lang/nl/lang.php
  modules/backend/models/EditorSetting.php
  modules/backend/models/editorsetting/fields.yaml
Labels: Status: Revision Needed, Type: Enhancement

#3694 Translation catalan
  modules/backend/lang/ca/lang.php
  modules/backend/models/Preference.php
  modules/cms/lang/ca/lang.php
  modules/system/assets/js/lang/lang.ca.js
  modules/system/lang/ca/client.php
  modules/system/lang/ca/lang.php
  modules/system/lang/ca/validation.php
  modules/system/lang/en/lang.php
Labels: Status: Completed, Type: Enhancement

#3688 Add Same-Site Cookie configuration option
  config/session.php
Labels: Status: Revision Needed, Type: Maintenance

#3699 Remove duplicate attribute class
  plugins/october/demo/components/todo/list.htm
Labels: Type: Maintenance

#3696 Updated to log when name is changed
  modules/cms/models/ThemeLog.php
Labels: Status: Completed, Type: Maintenance

#3703 Modify the Markup Tags layout
  modules/backend/models/editorsetting/fields.yaml
Labels: Type: Maintenance

#3705 Fix sorting icon
  modules/cms/widgets/templatelist/partials/_toolbar.htm
Labels: Type: Maintenance

#3704 Add functionality to use a model method to provide the availableColors for the color-picker widget
  modules/backend/formwidgets/ColorPicker.php
  modules/backend/lang/en/lang.php
  modules/backend/lang/nl/lang.php
Labels: Status: Revision Needed, Type: Conceptual Enhancement

#3718 Remove hard height constraint from previewing uploaded images
  modules/backend/formwidgets/FileUpload.php
Labels: Type: Maintenance

#3737 Update reportcontainer.less
  modules/backend/widgets/reportcontainer/assets/less/reportcontainer.less
Labels: Type: Maintenance
