Repository octobercms/october, pull requests merged in 2018-12, with the labels that each got.

#3526 Improved availability of the backend inspector outside of dragscroll elements
  modules/cms/assets/js/october.cmspage.js
Labels: Status: Completed, Type: Maintenance

#3546 Adds i18n support for the form field default property
  modules/backend/widgets/Form.php
Labels: Status: Completed, Type: Maintenance

#3536 Make media URLs in accordance with the Link Policy
  modules/system/classes/MediaLibrary.php
Labels: Status: Completed, Type: Maintenance

#3950 Revert changes made to self.hide after ajax
  modules/system/assets/ui/js/popup.js
Labels: Status: In Progress, Type: Maintenance

#3539 Added support for `dependsOn` with relationships
  modules/backend/behaviors/relationcontroller/assets/js/october.relation.js
  modules/backend/behaviors/relationcontroller/partials/_button_delete.htm
  modules/backend/behaviors/relationcontroller/partials/_button_remove.htm
  modules/backend/behaviors/relationcontroller/partials/_button_unlink.htm
  modules/backend/behaviors/relationcontroller/partials/_manage_form.htm
  modules/backend/behaviors/relationcontroller/partials/_manage_list.htm
Labels: Status: Completed, Type: Enhancement

#3953 Fix max & min items is repeater when using groups
  modules/backend/formwidgets/repeater/assets/js/repeater.js
Labels: Status: Completed, Type: Maintenance

#3960 Add Moments TimeZone Data
  modules/system/assets/ui/vendor/moment/moment-timezone-with-data.js
Labels: Status: Completed, Type: Maintenance

#3446 Added trigger change event
  modules/backend/formwidgets/mediafinder/assets/js/mediafinder.js
Labels: Status: Completed, Type: Maintenance

#3956 Prevent plugins that cannot be instantiated from being loaded
  modules/system/classes/PluginManager.php
  tests/fixtures/plugins/testvendor/goto/Plugin.php
  tests/unit/system/classes/PluginManagerTest.php
Labels: Status: Completed, Type: Maintenance

#3809 Added morphTo to list of singular relations
  modules/backend/traits/FormModelSaver.php
Labels: Status: Completed, Type: Maintenance

#3966 Update jquery.isotope library from v1.5.26 to v3.0.6
  modules/backend/widgets/reportcontainer/assets/vendor/isotope/jquery.isotope.js
  modules/backend/widgets/reportcontainer/assets/vendor/isotope/jquery.isotope.min.js
Labels: Status: Completed, Type: Maintenance

#3973 Remove dead HTTP Header
  modules/backend/layouts/_head.htm
  modules/backend/layouts/auth.htm
Labels: Status: Completed, Type: Maintenance

#3970 Fix 'hide()' called for a closed popup
  modules/system/assets/ui/js/popup.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Completed, Type: Maintenance

#3975 Add reset search (X) to toolbar search input
  modules/backend/widgets/search/partials/_search.htm
  modules/system/assets/ui/less/toolbar.less
  modules/system/assets/ui/storm.css
Labels: Status: Completed, Type: Maintenance

#3980 Datatable dropdown usability tweaks
  modules/backend/widgets/table/assets/css/table.css
  modules/backend/widgets/table/assets/js/build-min.js
  modules/backend/widgets/table/assets/js/table.js
  modules/backend/widgets/table/assets/js/table.processor.dropdown.js
  modules/backend/widgets/table/assets/less/table.less
Labels: Status: Completed, Type: Enhancement

#3361 Replace URL parameters dynamically without needing a list in advance
  modules/backend/behaviors/FormController.php
  modules/backend/widgets/Lists.php
Labels: Status: Completed, Type: Maintenance

#3995 Removed the deprecated hotkeyMac
  modules/backend/formwidgets/codeeditor/assets/js/codeeditor.js
Labels: Status: Completed, Type: Maintenance

#3990 Add the format parameter of the backend Lists text column type
  modules/backend/widgets/Lists.php
Labels: Status: Completed, Type: Enhancement

#3977 NestedForm Form Widget
  modules/backend/ServiceProvider.php
  modules/backend/formwidgets/NestedForm.php
  modules/backend/formwidgets/nestedform/assets/css/nestedform.css
  modules/backend/formwidgets/nestedform/assets/less/nestedform.less
  modules/backend/formwidgets/nestedform/partials/_nestedform.htm
Labels: Status: Completed, Type: Enhancement

#4000 added option as alias for alt
  modules/system/assets/ui/js/input.hotkey.js
Labels: Type: Maintenance

#4001 added the event to the callback
  modules/system/assets/ui/js/input.hotkey.js
Labels: Type: Maintenance

#4004 ES translations update
  modules/system/lang/es/lang.php
Labels: Status: Completed, Type: Maintenance

#4023 Run tests on PHP 7.3
  .travis.yml
Labels: Status: Completed, Type: Maintenance

#4021 Rename and deprecate prepareModel method in Lists widget
  modules/backend/behaviors/ImportExportController.php
  modules/backend/widgets/Lists.php
Labels: Status: Completed, Type: Maintenance
