Repository octobercms/october, pull requests merged in 2018-07, with the labels that each got.

#3626 Add config flag for allowing insecure paths (#3619)
  config/cms.php
  modules/system/traits/ConfigMaker.php
  modules/system/traits/ViewMaker.php
Labels: Status: Review Needed, Type: Maintenance

#3240 Select from framework asset options for #2753
  modules/cms/twig/FrameworkNode.php
  modules/system/ServiceProvider.php
  modules/system/assets/css/framework.extras-min.css
  modules/system/assets/js/framework-min.js
  modules/system/assets/js/framework.combined-min.js
  modules/system/assets/js/framework.combined.js
  modules/system/classes/CombineAssets.php
Labels: Status: Review Needed, Type: Maintenance

#3638 adding align support to non sortable list columns
  modules/backend/widgets/lists/partials/_list_head_row.htm
Labels: Type: Maintenance

#3644 Add cookie configuration file
  config/cookie.php
Labels: Status: Completed, Type: Conceptual Enhancement

#3633 Allow tabs to be closed with middle click...
  modules/system/assets/ui/js/tab.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Completed, Type: Enhancement

#3651 PHP 7.2
  .travis.yml
Labels: Type: Maintenance
