Repository octobercms/october, pull requests merged in 2018-04, with the labels that each got.

#3494 Add humans.txt file to october:mirror command
  modules/system/console/OctoberMirror.php
Labels: Type: Maintenance

#3509 Added align property to list columns definition
  modules/backend/classes/ListColumn.php
  modules/backend/widgets/lists/partials/_list_body_row.htm
  modules/backend/widgets/lists/partials/_list_head_row.htm
  modules/system/assets/ui/less/list.less
  modules/system/assets/ui/storm.css
Labels: Status: Response Needed, Type: Enhancement

#3522 Add alignment and size options in loader indicator
  modules/system/assets/ui/js/loader.base.js
  modules/system/assets/ui/storm-min.js
Labels: Type: Maintenance

#3524 Add searchOnEnter option to make the Search widget fire on enter key
  modules/backend/widgets/Search.php
  modules/backend/widgets/search/partials/_search.htm
Labels: Status: Revision Needed, Type: Enhancement

#3514 Update vietnamese translation
  modules/backend/lang/vn/lang.php
  modules/backend/models/Preference.php
  modules/cms/lang/vn/lang.php
  modules/system/assets/js/lang/lang.vn.js
  modules/system/lang/en/lang.php
  modules/system/lang/et/lang.php
  modules/system/lang/lt/lang.php
  modules/system/lang/nl/lang.php
  modules/system/lang/pt-pt/lang.php
  modules/system/lang/vn/client.php
  modules/system/lang/vn/lang.php
  modules/system/lang/vn/validation.php
Labels: Status: Revision Needed, Type: Enhancement

#3523 Fix for missing _group field when saving data from a nested group repeater
  modules/backend/formwidgets/repeater/partials/_repeater_item.htm
Labels: Status: Review Needed, Type: Maintenance
