Repository octobercms/october, pull requests merged in 2018-11, with the labels that each got.

#3902 Update the Modernizr library - from 2.8.3 to 3.6.0
  modules/system/assets/ui/vendor/modernizr/modernizr.js
Labels: Status: Review Needed, Type: Maintenance

#3844 Fix filter popovers in modals
  modules/system/assets/ui/js/filter.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Completed, Type: Maintenance

#3898 fix hide event firing twice
  modules/system/assets/ui/js/popup.js
Labels: Status: Review Needed, Type: Maintenance

#3916 Escape output to minimize potential XSS opportunities
  modules/system/controllers/updates/_plugin_form.htm
  modules/system/controllers/updates/_project_form.htm
  modules/system/controllers/updates/_theme_form.htm
Labels: Type: Maintenance

#3453 Placeholder for TagList
  modules/backend/formwidgets/TagList.php
  modules/backend/formwidgets/taglist/partials/_taglist.htm
  modules/system/assets/ui/less/select.less
  modules/system/assets/ui/less/select.variables.less
Labels: Status: Completed, Type: Maintenance

#3923 Fix for not showing disabled plugins
  modules/backend/classes/BackendController.php
Labels: Status: Revision Needed, Type: Maintenance

#3924 Escape output to prevent XSS injections
  modules/backend/behaviors/reordercontroller/partials/_records.htm
  modules/backend/widgets/search/partials/_search.htm
  modules/system/controllers/maillayouts/update.htm
  modules/system/controllers/mailpartials/update.htm
  modules/system/controllers/mailtemplates/update.htm
  modules/system/controllers/requestlogs/_referer_field.htm
Labels: Status: Completed, Type: Maintenance

#3926 ci: add missing meyfa/phpunit-assert-gd
  composer.json
Labels: Type: Maintenance

#3919 Add alias for jquery migrate (fixes #3917)
  modules/backend/assets/js/vendor/jquery-and-migrate.min.js
  modules/system/classes/CombineAssets.php
Labels: Status: Completed, Type: Maintenance

#3927 Add TimePicker.placement = auto (only supports: top/bottom position)
  modules/system/assets/ui/js/datepicker.js
  modules/system/assets/ui/storm-min.js
  modules/system/assets/ui/vendor/clockpicker/js/jquery-clockpicker.js
Labels: Status: Completed, Type: Maintenance

#3163 Fixes #3119
  modules/backend/formwidgets/recordfinder/partials/_container.htm
  modules/backend/formwidgets/recordfinder/partials/_recordfinder.htm
  modules/backend/widgets/form/partials/_field_dropdown.htm
  modules/backend/widgets/form/partials/_field_switch.htm
  modules/system/assets/ui/less/form.base.less
Labels: Priority: Medium, Status: Completed, Type: Maintenance

#3041 Fixed bug caused by not existing use statement
  modules/cms/twig/DebugExtension.php
Labels: Priority: Low, Type: Maintenance

#3890 tiny fix to css issue
  modules/system/assets/ui/less/dropdown.less
  modules/system/controllers/updates/_list_manage_toolbar.htm
  modules/system/lang/en/lang.php
Labels: Status: Review Needed, Type: Maintenance

#3544 Update RelationController.php
  modules/backend/behaviors/RelationController.php
Labels: Status: Completed, Type: Maintenance

#2721 Hotkey improvements
  modules/system/assets/ui/docs/input-hotkey.md
  modules/system/assets/ui/js/input.hotkey.js
Labels: Priority: Medium, Status: Review Needed, Type: Maintenance

#3664 Extend opcache check if it is enabled
  modules/cms/classes/CodeParser.php
Labels: Status: Completed, Type: Maintenance

#3933 Delete single asset file.
  modules/cms/classes/Asset.php
Labels: Status: Completed, Type: Maintenance
