Repository octobercms/october, pull requests merged in 2018-06, with the labels that each got.

#3578 Missing and invalid polish translations fixes
  modules/backend/lang/pl/lang.php
  modules/system/lang/ar/lang.php
  modules/system/lang/en/lang.php
  modules/system/lang/et/lang.php
  modules/system/lang/fa/lang.php
  modules/system/lang/lt/lang.php
  modules/system/lang/nl/lang.php
  modules/system/lang/pl/lang.php
  modules/system/lang/vn/lang.php
Labels: Type: Maintenance

#3580 MediaLibrary test updates
  tests/unit/system/classes/MediaLibraryTest.php
Labels: Type: Maintenance

#3373 Use config variable for data cache key.
  config/cache.php
  modules/cms/classes/CodeParser.php
Labels: Status: Review Needed, Type: Maintenance

#3604 Fix Security issue in media manager
  modules/backend/widgets/MediaManager.php
Labels: Priority: Medium, Status: In Progress, Type: Maintenance
