Repository octobercms/october, pull requests merged in 2018-03, with the labels that each got.

#3421 Fixing stale cache issue
  modules/cms/classes/CodeParser.php
Labels: Status: Response Needed, Type: Maintenance

#3379 Plugin Management UX Improvements
  modules/system/controllers/Updates.php
  modules/system/controllers/updates/_disable_form.htm
  modules/system/controllers/updates/_is_enabled.htm
  modules/system/controllers/updates/_is_unfrozen.htm
  modules/system/controllers/updates/_list_manage_toolbar.htm
  modules/system/controllers/updates/manage.htm
  modules/system/lang/en/lang.php
  modules/system/models/pluginversion/columns_manage.yaml
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#3430 Add Cache-Control header for combine assets
  modules/system/classes/CombineAssets.php
Labels: Status: Review Needed, Type: Maintenance

#3432 Cache page number in List widget
  modules/backend/widgets/Lists.php
Labels: Status: Completed, Type: Enhancement

#3450 Update ImportModel.php
  modules/backend/models/ImportModel.php
Labels: Status: Review Needed, Type: Maintenance

#3296 Adding Arabic language
  modules/backend/lang/ar/lang.php
  modules/backend/models/Preference.php
  modules/cms/lang/ar/lang.php
  modules/system/lang/ar/client.php
  modules/system/lang/ar/lang.php
  modules/system/lang/en/lang.php
Labels: Status: Completed, Type: Conceptual Enhancement

#3465 Set a trigger condition to be a field from the parent form for a field in a repeater
  modules/backend/classes/FormField.php
Labels: Status: Revision Needed, Type: Conceptual Enhancement

#3363 Develop fix type juggling, strings to ::class accross all project, flow structs
  modules/cms/ServiceProvider.php
  modules/cms/classes/Controller.php
  modules/cms/classes/Layout.php
  modules/cms/classes/MediaLibrary.php
  modules/cms/classes/Page.php
  modules/cms/components/Resources.php
  modules/cms/components/ViewBag.php
  modules/cms/controllers/Index.php
  modules/cms/controllers/Themes.php
  modules/cms/helpers/Cms.php
  modules/cms/helpers/File.php
  modules/cms/models/ThemeData.php
  modules/cms/twig/Loader.php
  modules/system/twig/Loader.php
  tests/fixtures/cms/reference/namespaces-aliases.php.stub
  tests/fixtures/cms/reference/namespaces.php.stub
  tests/unit/cms/classes/CodeParserTest.php
Labels: Status: Review Needed, Type: Maintenance
