Repository octobercms/october, pull requests merged in 2018-09, with the labels that each got.

#3750 Fixed the readonly issue
  modules/backend/classes/FormField.php
Labels: Type: Maintenance

#3754 Change the lang code in the html templates
  modules/backend/views/access_denied.php
  modules/backend/views/no_database.php
  modules/cms/views/404.php
  modules/cms/views/error.php
Labels: Type: Maintenance

#3765 Added method getLayout() to Controller
  modules/cms/classes/Controller.php
Labels: Status: Response Needed, Type: Conceptual Enhancement

#3777 Removed css rule that makes filelist entries unreadable on touchscreen devices
  modules/backend/assets/css/october.css
  modules/backend/assets/less/controls/filelist.less
Labels: Type: Maintenance

#3778 Fixes issue 3741 - MediaLibrary filenames too strict
  modules/system/classes/MediaLibrary.php
  tests/unit/system/classes/MediaLibraryTest.php
Labels: Type: Maintenance

#3761 Correcting the class for correctly displaying the bootstrap grid in the tabs
  modules/backend/assets/less/layout/layout.less
  modules/backend/classes/FormTabs.php
Labels: Status: Response Needed, Type: Conceptual Enhancement

#3793 Filter group translatable options
  modules/backend/widgets/Filter.php
Labels: Type: Maintenance

#3798 Fix input trigger on source field types with multiple selected values
  modules/system/assets/ui/js/input.trigger.js
  modules/system/assets/ui/storm-min.js
Labels: Type: Maintenance

#3799 Modify language label
  modules/backend/lang/nl/lang.php
Labels: Type: Maintenance

#3803 Add favicon to back-end login page
  modules/backend/layouts/auth.htm
Labels: Type: Maintenance

#3727 Add assets prefix implementation within combineToFile method
  modules/system/classes/CombineAssets.php
Labels: Status: Revision Needed, Type: Maintenance

#3192 Make inline CSS for email layouts optional
  modules/system/classes/MailManager.php
  modules/system/database/migrations/2017_10_23_000024_Db_System_Mail_Layouts_Add_Options_Field.php
  modules/system/lang/de/lang.php
  modules/system/lang/en/lang.php
  modules/system/models/MailLayout.php
  modules/system/models/maillayout/fields.yaml
Labels: Priority: Medium, Status: Completed, Type: Maintenance

#3802 Fix asset combiner
  modules/system/traits/AssetMaker.php
  tests/unit/system/traits/AssetMakerTest.php
Labels: Type: Maintenance

#3479 Fix mail.beforeAddContent listener to use the $plain argument as well
  modules/system/ServiceProvider.php
  modules/system/classes/MailManager.php
Labels: Type: Maintenance

#3787 Adds missing Content-Type header to CSV-export. (mentioned in #1313)
  modules/backend/models/ExportModel.php
  tests/unit/backend/models/ExportModelTest.php
Labels: Type: Maintenance

#3824 Fix (Trait 'AssertGD\GDAssertTrait' not found)
  composer.json
Labels: Type: Maintenance
