Repository octobercms/october, pull requests merged in 2019-10, with the labels that each got.

#4653 Added getConfig helper method to get config values
  modules/backend/classes/ListColumn.php
Labels: Status: Completed, Type: Enhancement

#4660 Fix bulk actions on plugins
  modules/system/controllers/updates/_list_manage_toolbar.htm
Labels: Status: Completed, Type: Maintenance

#4654 Allow relation widget to be ordered by author
  modules/backend/formwidgets/Relation.php
Labels: Status: In Progress, Type: Enhancement

#4666 Prevent flash of unstyled tabs on page load
  modules/backend/widgets/form/partials/_form_tabs.htm
  modules/system/assets/ui/js/tab.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Completed, Type: Maintenance

#4667 added mailgun endpoint to services config, fixes issue #3846
  config/services.php
Labels: Type: Maintenance

#4668 Update French translations
  modules/system/assets/js/lang/lang.fr.js
  modules/system/lang/fr/client.php
  modules/system/lang/fr/lang.php
  modules/system/lang/fr/validation.php
Labels: Status: Completed, Type: Maintenance

#4657 fix issue 4185
  modules/cms/classes/Router.php
Labels: Status: Completed, Type: Maintenance

#4673 Fixes #4625
  modules/backend/behaviors/relationcontroller/partials/_manage_form.htm
Labels: Status: Completed, Type: Maintenance

#4676 Update Dutch (NL_nl) translation
  modules/backend/lang/nl/lang.php
  modules/cms/lang/nl/lang.php
  modules/system/lang/nl/lang.php
Labels: Status: Completed, Type: Maintenance

#4674 Fix #3415, #4672
  modules/backend/formwidgets/Repeater.php
Labels: Status: Review Needed, Type: Enhancement

#4645 Fix sync command, minor cleanup
  modules/system/console/ThemeSync.php
  tests/unit/system/classes/AutoDatasourceTest.php
Labels: Status: Completed, Type: Maintenance

#4520 Add permission support for forms, lists and filters
  composer.json
  modules/backend/widgets/Filter.php
  modules/backend/widgets/Form.php
  modules/backend/widgets/Lists.php
  tests/PluginTestCase.php
  tests/TestCase.php
  tests/concerns/InteractsWithAuthentication.php
  tests/fixtures/backend/models/UserFixture.php
  tests/unit/backend/widgets/FilterTest.php
  tests/unit/backend/widgets/FormTest.php
  tests/unit/backend/widgets/ListsTest.php
Labels: Status: Completed, Type: Enhancement

#4687 Update validation.php
  modules/system/lang/ru/validation.php
Labels: Status: Completed, Type: Maintenance

#4689 Update portuguese translation
  modules/backend/lang/pt-pt/lang.php
Labels: Status: Completed, Type: Maintenance

#4682 Improved Hungarian translation
  modules/backend/lang/hu/lang.php
  modules/system/lang/hu/lang.php
Labels: Status: Completed, Type: Maintenance

#4706 Add some "clear" classes for fields
  modules/system/assets/ui/less/form.less
  modules/system/assets/ui/storm.css
Labels: Status: Completed, Type: Maintenance

#4720 Implement XSRF checking for AJAX handlers
  modules/cms/classes/Controller.php
  modules/system/assets/js/framework-min.js
  modules/system/assets/js/framework.combined-min.js
  modules/system/assets/js/framework.js
Labels: Status: Revision Needed, Testing Needed, Type: Maintenance

#4727 Minor : Typo in "Automatically run migrations on login"
  config/cms.php
Labels: Status: Completed, Type: Maintenance
