Repository octobercms/october, pull requests merged in 2019-04, with the labels that each got.

#4199 Append the color picker modal to parent element
  modules/backend/formwidgets/colorpicker/assets/js/colorpicker.js
Labels: Status: Completed, Type: Maintenance

#4166 Markdown parse markdown formwidget preview
  modules/backend/formwidgets/markdowneditor/partials/_markdowneditor.htm
Labels: Status: Completed, Type: Maintenance

#4200 Make default format options configurable
  modules/backend/behaviors/ImportExportController.php
Labels: Status: Completed, Type: Enhancement

#4217 add oc.inputPreset.beforeUpdate plugin hook
  modules/system/assets/ui/js/input.preset.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Completed, Type: Maintenance

#4231 Fix JS error when calling getDropdownOptions handler in DataTable widget
  modules/backend/formwidgets/DataTable.php
Labels: Status: Completed, Type: Maintenance

#4239 add $options param to formRenderField
  modules/backend/behaviors/FormController.php
Labels: Status: Completed, Type: Maintenance

#4236 Added overflow rules to preview form-control
  modules/system/assets/ui/less/form.less
  modules/system/assets/ui/storm.css
Labels: Status: Completed, Type: Maintenance

#4235 Do not hardcode handler name
  modules/backend/widgets/filter/partials/_scope_text.htm
Labels: Status: Completed, Type: Maintenance

#4198 Improve Arabic Translation
  modules/backend/lang/ar/lang.php
Labels: Status: Review Needed, Type: Maintenance

#4250 Improved Hungarian translation
  modules/backend/formwidgets/richeditor/assets/vendor/froala/js/languages/hu.js
  modules/backend/lang/hu/lang.php
  modules/system/lang/hu/lang.php
Labels: Type: Maintenance

#4242 Additional fixes to #4234
  modules/backend/formwidgets/Repeater.php
  modules/backend/formwidgets/repeater/partials/_repeater.htm
Labels: Status: Review Needed, Testing Needed, Type: Maintenance

#4256 Fix for issue #4255
  modules/backend/formwidgets/RecordFinder.php
Labels: Type: Maintenance

#4092 Fix CloudFlare Rocket Loader break the script loading order.
  modules/backend/formwidgets/FileUpload.php
  modules/backend/widgets/Form.php
  modules/system/traits/AssetMaker.php
Labels: Status: Revision Needed, Type: Maintenance

#4234 Simplify Repeater Logic
  modules/backend/formwidgets/Repeater.php
  modules/backend/formwidgets/repeater/partials/_repeater.htm
  modules/backend/formwidgets/repeater/partials/_repeater_item.htm
Labels: Status: Completed, Type: Maintenance

#4269 Fix mediafinder error message
  modules/backend/formwidgets/mediafinder/assets/js/mediafinder.js
  modules/backend/formwidgets/mediafinder/partials/_image_single.htm
Labels: Status: Completed, Type: Maintenance

#4273 reuse formWidget model
  modules/backend/formwidgets/FileUpload.php
Labels: Status: Completed, Type: Maintenance

#4259 Update jQuery from V3.3.1 to V3.4.0
  modules/backend/assets/js/vendor/jquery.min.js
  modules/system/assets/ui/vendor/pikaday/README.md
Labels: Status: Completed, Type: Maintenance

#4272 Added Preload and Version Numbers
  modules/backend/layouts/_head.htm
  modules/backend/layouts/auth.htm
Labels: Status: Completed, Type: Maintenance

#4276 Finish theme:sync command
  modules/cms/ServiceProvider.php
  modules/system/console/ThemeSync.php
Labels: Status: Revision Needed, Type: Enhancement

#4238 Abort old track input requests
  modules/system/assets/js/framework-min.js
  modules/system/assets/js/framework.combined-min.js
  modules/system/assets/js/framework.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Completed, Type: Maintenance

#4270 Add theme config cache
  modules/cms/classes/Theme.php
Labels: Status: Completed, Type: Maintenance

#3085 Fix for RichEditor root page links being returned with empty hrefs.
  modules/backend/formwidgets/RichEditor.php
Labels: Priority: High, Type: Maintenance

#3164 Add getters for relation widgets
  modules/backend/behaviors/RelationController.php
Labels: Status: Completed, Type: Maintenance

#3282 Update es-ar/lang.php
  modules/backend/lang/es-ar/lang.php
Labels: Status: Revision Needed, Type: Maintenance

#3573 fix typing
  config/session.php
Labels: Status: Completed, Type: Maintenance

#3712 If using database, don't call plugin task scheduling before initial system migration
  modules/system/ServiceProvider.php
  modules/system/classes/UpdateManager.php
Labels: Status: Review Needed, Type: Maintenance

#3832 Update EventLog.php
  modules/system/models/EventLog.php
Labels: Status: Completed, Type: Maintenance

#3904 Modfied error maker with extra funcitonality
  modules/backend/traits/ErrorMaker.php
Labels: Status: Completed, Type: Maintenance

#3993 Update richeditor.css & _froala.less
  modules/backend/formwidgets/richeditor/assets/css/richeditor.css
  modules/backend/formwidgets/richeditor/assets/less/_froala.less
Labels: Status: Completed, Type: Maintenance

#4079 Support for morphOne relation in backend column list
  modules/backend/widgets/Lists.php
Labels: Status: Completed, Type: Maintenance

#4162 Add support for package discovery
  composer.json
Labels: Status: Review Needed, Type: Maintenance

#4287 max url field length is 191 bytes
  modules/system/models/RequestLog.php
Labels: Status: Completed, Type: Maintenance

#4284 Fix multiple config themes
  modules/cms/classes/Theme.php
Labels: Status: Completed, Type: Maintenance

#4290 Fix input preset converter for Vietnamese
  modules/system/assets/ui/js/input.preset.js
  modules/system/assets/ui/storm-min.js
Labels: Type: Maintenance

#4103 Remove data-slidable for tabs
  modules/backend/widgets/form/partials/_section.htm
Labels: Status: Completed, Type: Maintenance

#4296 Escape widgets values
  modules/backend/formwidgets/colorpicker/partials/_colorpicker.htm
  modules/backend/formwidgets/mediafinder/partials/_file_single.htm
  modules/backend/formwidgets/mediafinder/partials/_image_single.htm
  modules/backend/widgets/filter/partials/_scope_text.htm
  modules/backend/widgets/form/partials/_field_checkboxlist.htm
  modules/backend/widgets/form/partials/_field_dropdown.htm
  modules/backend/widgets/form/partials/_field_radio.htm
Labels: Status: Completed, Type: Maintenance

#4075 Seperate proprietary and ocms js asset bundles
  modules/backend/ServiceProvider.php
  modules/backend/formwidgets/RichEditor.php
  modules/backend/formwidgets/richeditor/assets/js/build-min.js
  modules/backend/formwidgets/richeditor/assets/js/build-oc-plugins-min.js
  modules/backend/formwidgets/richeditor/assets/js/build-oc-plugins.js
  modules/backend/formwidgets/richeditor/assets/js/build.js
Labels: Status: Review Needed, Type: Maintenance

#4304 fix backend list scrolling on mobile
  modules/system/assets/ui/less/list.less
  modules/system/assets/ui/storm.css
Labels: Status: Completed, Type: Maintenance

#4301 Prevent subject and password from being HTML encoded in the invite email
  modules/backend/views/mail/invite.htm
Labels: Status: Completed, Type: Maintenance
