Repository octobercms/october, pull requests merged in 2019-03, with the labels that each got.

#4088 Service Workers Invalid security token and Clear Site Data HTTP Header
  modules/backend/assets/js/auth/uninstall-sw.js
  modules/backend/controllers/Auth.php
Labels: Status: Review Needed, Type: Maintenance

#4191 Skipped test
  tests/unit/plugins/database/HasManyModelTest.php
Labels: Type: Maintenance

#4179 Update French Translation
  modules/backend/lang/fr/lang.php
Labels: Status: Completed, Type: Maintenance

#4193 Reuse the model instance from Form widget
  modules/backend/behaviors/RelationController.php
Labels: Status: Completed, Type: Maintenance

#4160 Use Form getSaveData method when saving form widgets within repeaters
  modules/backend/formwidgets/Repeater.php
  modules/backend/widgets/Form.php
Labels: Status: Completed, Type: Maintenance

#4202 Display backend 404 for non-existent backend urls if CMS module is not loaded
  modules/backend/classes/BackendController.php
Labels: Status: Completed, Type: Maintenance

#4116 Fix form recordpicker disabled behaviour. Fix #3983
  modules/backend/widgets/Form.php
Labels: Status: Completed, Type: Maintenance

#4154 Fix issue with list filters when more filters appear on page.
  modules/system/assets/ui/js/filter.dates.js
  modules/system/assets/ui/js/filter.js
  modules/system/assets/ui/js/filter.numbers.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Completed, Type: Maintenance

#4190 Delay backend controller middleware until after request is processed
  modules/backend/classes/BackendController.php
  modules/backend/controllers/Auth.php
Labels: Status: Review Needed, Type: Enhancement

#4211 Add support for file names with multiple dots
  modules/system/classes/VersionManager.php
  tests/unit/system/classes/VersionManagerTest.php
Labels: Status: Completed, Type: Maintenance

#4169 Fix popup loading indicator
  modules/system/assets/ui/js/popup.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Completed, Type: Maintenance

#4207 Allow List Widget configs to add CSS classes to head column cell
  modules/backend/classes/ListColumn.php
  modules/backend/widgets/lists/partials/_list_head_row.htm
Labels: Status: Completed, Type: Maintenance

#3965 Update Dashboard Columns from 10 to 12
  modules/backend/widgets/ReportContainer.php
  modules/backend/widgets/reportcontainer/assets/css/reportcontainer.css
  modules/backend/widgets/reportcontainer/assets/js/reportcontainer.js
  modules/backend/widgets/reportcontainer/assets/less/reportcontainer.less
Labels: Status: Response Needed, Type: Conceptual Enhancement

#4218 Fixes #4209.
  modules/cms/classes/CmsCompoundObject.php
  modules/cms/classes/CmsException.php
  modules/cms/classes/CodeParser.php
  modules/cms/classes/Controller.php
  modules/cms/twig/ComponentNode.php
  modules/cms/twig/ComponentTokenParser.php
  modules/cms/twig/ContentNode.php
  modules/cms/twig/ContentTokenParser.php
  modules/cms/twig/DebugExtension.php
  modules/cms/twig/DefaultNode.php
  modules/cms/twig/DefaultTokenParser.php
  modules/cms/twig/Extension.php
  modules/cms/twig/FlashNode.php
  modules/cms/twig/FlashTokenParser.php
  modules/cms/twig/FrameworkNode.php
  modules/cms/twig/FrameworkTokenParser.php
  modules/cms/twig/Loader.php
  modules/cms/twig/PageNode.php
  modules/cms/twig/PageTokenParser.php
  modules/cms/twig/PartialNode.php
  modules/cms/twig/PartialTokenParser.php
  modules/cms/twig/PlaceholderNode.php
  modules/cms/twig/PlaceholderTokenParser.php
  modules/cms/twig/PutNode.php
  modules/cms/twig/PutTokenParser.php
  modules/cms/twig/ScriptsNode.php
  modules/cms/twig/ScriptsTokenParser.php
  modules/cms/twig/StylesNode.php
  modules/cms/twig/StylesTokenParser.php
  modules/system/ServiceProvider.php
  modules/system/classes/ErrorHandler.php
  modules/system/classes/MarkupManager.php
  modules/system/twig/Engine.php
  modules/system/twig/Extension.php
  modules/system/twig/Loader.php
  modules/system/twig/MailPartialNode.php
  modules/system/twig/MailPartialTokenParser.php
  tests/unit/cms/classes/ControllerTest.php
Labels: Status: Completed, Type: Maintenance

#4221 update lang(ru) in scopes
  modules/system/lang/ru/client.php
Labels: Status: Completed, Type: Maintenance

#4159 Overriding env DB parameters on plugin tests
  config/database.php
  modules/system/console/OctoberEnv.php
  tests/PluginTestCase.php
  tests/README.md
Labels: Status: Completed, Type: Maintenance

#4225 Fix for #4224
  modules/system/classes/VersionManager.php
  tests/unit/system/classes/VersionManagerTest.php
Labels: Status: Completed, Type: Maintenance
