Repository octobercms/october, pull requests merged in 2019-12, with the labels that each got.

#4746 Public getters for backend list widget. getSortColumn and getSortDirection
  modules/backend/widgets/Lists.php
Labels: Status: Completed, Type: Maintenance

#4802 Prevent race condition on recordfinder remove
  modules/backend/formwidgets/recordfinder/partials/_recordfinder.htm
Labels: Status: Completed, Type: Maintenance

#4564 Support additional file name and path characters in media manager
  modules/system/classes/MediaLibrary.php
  tests/unit/system/classes/MediaLibraryTest.php
Labels: Testing Needed, Type: Maintenance

#4807 Fixed DataTable dropdowns in Modals
  modules/backend/widgets/table/assets/js/build-min.js
  modules/backend/widgets/table/assets/js/table.processor.dropdown.js
Labels: Status: Review Needed, Type: Bug

#4658 Added lazy loading for backend form tabs
  modules/backend/classes/FormTabs.php
  modules/backend/widgets/Form.php
  modules/backend/widgets/form/assets/js/october.form.js
  modules/backend/widgets/form/partials/_form_tabs.htm
  modules/backend/widgets/form/partials/_form_tabs_lazy.htm
Labels: Status: Review Needed, Testing Needed, Type: Enhancement

#4769 safemode fix
  modules/cms/classes/CmsCompoundObject.php
  modules/cms/classes/layout/fields.yaml
  modules/cms/classes/page/fields.yaml
  modules/cms/classes/partial/fields.yaml
  modules/cms/controllers/Index.php
  modules/cms/controllers/index/_safemode_notice.htm
  modules/cms/helpers/Cms.php
  modules/cms/lang/en/lang.php
Labels: Status: Completed, Type: Maintenance

#4737 Adds the ability to override the column header label in list export.
  modules/backend/behaviors/ImportExportController.php
Labels: Status: Review Needed, Type: Maintenance

#4796 Slovenian language added
  modules/backend/formwidgets/richeditor/assets/vendor/froala/js/languages/sl.js
  modules/backend/lang/sl/lang.php
  modules/backend/models/Preference.php
  modules/cms/lang/sl/lang.php
  modules/system/assets/js/lang/lang.sl.js
  modules/system/lang/ar/lang.php
  modules/system/lang/en/lang.php
  modules/system/lang/et/lang.php
  modules/system/lang/fa/lang.php
  modules/system/lang/fi/lang.php
  modules/system/lang/lt/lang.php
  modules/system/lang/nl/lang.php
  modules/system/lang/pt-pt/lang.php
  modules/system/lang/sk/lang.php
  modules/system/lang/sl/client.php
  modules/system/lang/sl/lang.php
  modules/system/lang/sl/validation.php
  modules/system/lang/tr/lang.php
  modules/system/lang/vn/lang.php
Labels: Status: Review Needed, Type: Maintenance

#4680 Fix #4679: Unable to set customview path for relation list
  modules/backend/behaviors/RelationController.php
Labels: Status: Review Needed, Type: Enhancement

#4814 More strict checking of "add item" requests for child repeaters
  modules/backend/formwidgets/Repeater.php
Labels: Status: Review Needed, Type: Maintenance

#4652 Allow partial overrides in subfolders
  modules/cms/classes/ComponentPartial.php
  modules/cms/classes/Controller.php
  modules/cms/helpers/File.php
Labels: Testing Needed, Type: Maintenance

#4743 Make http_only cookies configurable
  config/session.php
  modules/backend/classes/Controller.php
Labels: Status: Completed, Type: Maintenance

#4566 Correctly display HTML entities in event log
  modules/system/assets/js/eventlogs/exception-beautifier.js
  modules/system/controllers/eventlogs/_field_message.htm
  modules/system/models/eventlog/fields.yaml
Labels: Type: Maintenance

#4741 Refresh Relation Manager on Unlink and Delete
  modules/backend/behaviors/RelationController.php
Labels: Priority: Medium, Status: Completed, Type: Maintenance

#4685 Adding two additional robots META fields to CMS.Pages
  modules/cms/classes/Page.php
  modules/cms/classes/page/fields.yaml
  modules/cms/lang/en/lang.php
  modules/cms/lang/ru/lang.php
Labels: Status: Completed, Type: Conceptual Enhancement

#4832 Revert "Adding two additional robots META fields to CMS.Pages"
  modules/cms/classes/Page.php
  modules/cms/classes/page/fields.yaml
  modules/cms/lang/en/lang.php
  modules/cms/lang/ru/lang.php
Labels: Status: Completed, Type: Maintenance

#4839 implement lazy loading for secondary tabs
  modules/backend/widgets/Form.php
  modules/backend/widgets/form/assets/js/october.form.js
  modules/backend/widgets/form/partials/_form_tabs.htm
Labels: Type: Enhancement, Type: Maintenance

#4841 Fix tap-targets on checkboxes
  modules/system/assets/ui/less/form.base.less
  modules/system/assets/ui/less/form.less
  modules/system/assets/ui/storm.css
Labels: Status: Completed, Type: Maintenance

#4836 Allow changing of Backend user passwords through CLI.
  modules/system/ServiceProvider.php
  modules/system/console/OctoberPasswd.php
Labels: Status: Review Needed, Type: Enhancement

#4852 Correct missing char in sk translation
  modules/system/lang/sk/lang.php
Labels: Type: Maintenance
