Repository octobercms/october, pull requests merged in 2019-01, with the labels that each got.

#4032 Fix the filter options will be escaped twice
  modules/backend/widgets/Filter.php
Labels: Type: Maintenance

#4015 Fixed the Delete and Enter key can't be captured
  modules/backend/formwidgets/richeditor/assets/js/richeditor.js
Labels: Status: Completed, Type: Maintenance

#4062 Fix default value translation
  modules/backend/widgets/Form.php
Labels: Status: Completed, Type: Maintenance

#4068 Fix reset search button issues
  modules/system/assets/ui/less/toolbar.less
  modules/system/assets/ui/storm.css
Labels: Status: Completed, Type: Maintenance

#4051 Added manual deleted_at checks
  modules/backend/classes/AuthManager.php
Labels: Status: Completed, Type: Maintenance

#4069 Tabs and tabels scrolling fix
  modules/backend/assets/css/october.css
  modules/backend/assets/js/october-min.js
  modules/backend/assets/js/october.scrollbar.js
  modules/backend/assets/js/october.sidepaneltab.js
  modules/backend/assets/less/controls/alert.less
  modules/backend/assets/less/controls/treeview.less
  modules/backend/assets/less/layout/layout.less
  modules/backend/widgets/reportcontainer/assets/js/reportcontainer.js
  modules/cms/assets/js/october.dragcomponents.js
  modules/system/assets/css/framework.extras-min.css
  modules/system/assets/js/eventlogs/exception-beautifier.links.js
  modules/system/assets/ui/js/drag.scroll.js
  modules/system/assets/ui/js/filter.js
  modules/system/assets/ui/js/inspector.editor.dropdown.js
  modules/system/assets/ui/js/loader.cursor.js
  modules/system/assets/ui/less/list.less
  modules/system/assets/ui/storm-min.js
  modules/system/assets/ui/storm.css
  modules/system/assets/ui/vendor/modernizr/modernizr.js
Labels: Status: Completed, Type: Maintenance

#3652 Override the Paginators defaultSimpleView
  modules/system/ServiceProvider.php
  modules/system/lang/el/lang.php
  modules/system/lang/en/lang.php
  modules/system/views/pagination/simple-default.blade.php
Labels: Status: Completed, Type: Maintenance

#4080 Fixes bugs with 'collapsed' saved to cookies
  modules/backend/assets/js/october-min.js
  modules/backend/assets/js/october.sidenav-tree.js
  modules/system/partials/_settings_menu_items.htm
Labels: Status: Completed, Type: Maintenance

#4058 Changed z-index
  modules/system/assets/ui/less/popover.less
Labels: Status: Completed, Type: Maintenance

#4060 Fix for #4053
  modules/system/assets/ui/js/select.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Review Needed, Type: Maintenance

#4098 Fix setting default values for repeater in update context
  modules/backend/formwidgets/Repeater.php
  modules/backend/widgets/Form.php
Labels: Status: Completed, Type: Maintenance
