Repository octobercms/october, pull requests merged in 2019-08, with the labels that each got.

#4514 Update __isset function to comply with the same checks as __get
  modules/cms/classes/CodeBase.php
Labels: Status: Completed, Type: Maintenance

#4434 Fix "widget not bound to controller" error for nested repeaters
  modules/backend/formwidgets/Repeater.php
Labels: Status: Completed, Type: Bug, Type: Maintenance

#4542 Add info how to fix the develop branch in CONTRIBUTING.md file
  .github/CONTRIBUTING.md
Labels: Status: Completed, Type: Maintenance

#4548 Standardise Array Declaration
  modules/backend/widgets/MediaManager.php
  modules/cms/controllers/Index.php
  modules/system/classes/VersionManager.php
  modules/system/lang/de/validation.php
  modules/system/lang/es-ar/validation.php
  modules/system/lang/id/validation.php
  modules/system/lang/lv/validation.php
  modules/system/lang/ro/validation.php
  modules/system/lang/sv/validation.php
  modules/system/lang/zh-cn/validation.php
  modules/system/lang/zh-tw/validation.php
  tests/unit/cms/classes/ControllerTest.php
  tests/unit/cms/classes/RouterTest.php
  tests/unit/system/classes/CoreLangTest.php
Labels: Status: Completed, Type: Maintenance

#4543 Minor Spelling Errors and Inconsistencies
  modules/cms/classes/AutoDatasource.php
  modules/cms/classes/Controller.php
  modules/cms/twig/Loader.php
Labels: Status: Completed, Type: Maintenance

#4529 Remove Theme Data on Theme Deletion
  modules/cms/classes/Theme.php
  modules/cms/classes/ThemeManager.php
Labels: Status: Completed, Type: Maintenance

#4528 Hide Active Theme's Delete Button
  modules/cms/controllers/themes/_theme_list_item.htm
Labels: Status: Completed, Type: Maintenance

#4500 Add warning when debug mode is enabled in status widget
  modules/backend/lang/en/lang.php
  modules/system/reportwidgets/Status.php
Labels: Status: Completed, Type: Maintenance

#4497 Add validator for navigation in backend
  modules/backend/classes/NavigationManager.php
Labels: Status: Completed, Type: Maintenance

#4541 Minor Formatting Corrections in Usage Comments
  modules/backend/classes/AuthManager.php
  modules/backend/classes/Controller.php
  modules/backend/classes/NavigationManager.php
  modules/backend/classes/WidgetManager.php
  modules/backend/widgets/Filter.php
  modules/backend/widgets/Form.php
  modules/backend/widgets/Lists.php
  modules/backend/widgets/MediaManager.php
  modules/cms/classes/CmsObject.php
  modules/cms/classes/ComponentBase.php
  modules/cms/classes/ComponentManager.php
  modules/cms/classes/Controller.php
  modules/cms/classes/Theme.php
  modules/system/classes/CombineAssets.php
  modules/system/classes/MailManager.php
  modules/system/classes/MarkupManager.php
  modules/system/classes/SettingsManager.php
  modules/system/console/OctoberMirror.php
Labels: Status: Completed, Type: Maintenance

#4525 Fix issues with removeReportWidget()
  modules/backend/classes/WidgetManager.php
Labels: Status: Completed, Type: Maintenance

#4536 Upload vendor file Spectrum V1.8.0
  modules/backend/formwidgets/colorpicker/assets/vendor/spectrum/spectrum.js
Labels: Status: Completed, Type: Maintenance

#4551 Mention the lang dependency
  modules/backend/assets/js/october.alert.js
Labels: Status: Completed, Type: Maintenance

#4544 Use Selected Dropdown Item as Collapsed Repeater Title
  modules/backend/formwidgets/repeater/assets/js/repeater.js
Labels: Status: Completed, Type: Enhancement

#4549 Allow decompiled Backend JS assets
  config/develop.php
  modules/backend/helpers/Backend.php
  modules/backend/helpers/exception/DecompileException.php
  modules/backend/lang/en/lang.php
  modules/backend/layouts/_head.htm
  modules/system/reportwidgets/Status.php
  tests/fixtures/backend/assets/compilation.js
  tests/fixtures/backend/assets/js/file1.js
  tests/fixtures/backend/assets/js/file2.js
  tests/fixtures/backend/assets/not-compilation.js
  tests/unit/backend/helpers/BackendHelperTest.php
Labels: Status: Completed, Type: Enhancement

#4555 Update Arabic language
  modules/system/lang/ar/lang.php
  modules/system/lang/ar/validation.php
Labels: Status: Completed, Type: Maintenance

#4567 Include file extension in combiner
  modules/system/classes/CombineAssets.php
Labels: Status: Completed, Type: Maintenance
