Repository octobercms/october, pull requests merged in 2019-06, with the labels that each got.

#3908 Database layer for the CMS objects
  config/cms.php
  modules/cms/ServiceProvider.php
  modules/cms/assets/js/october.cmspage.js
  modules/cms/classes/AutoDatasource.php
  modules/cms/classes/Meta.php
  modules/cms/classes/Theme.php
  modules/cms/controllers/Index.php
  modules/cms/controllers/index/_button_commit.htm
  modules/cms/controllers/index/_button_lastmodified.htm
  modules/cms/controllers/index/_button_reset.htm
  modules/cms/controllers/index/_common_toolbar_actions.htm
  modules/cms/controllers/index/_content_toolbar.htm
  modules/cms/controllers/index/_layout_toolbar.htm
  modules/cms/controllers/index/_page_toolbar.htm
  modules/cms/controllers/index/_partial_toolbar.htm
  modules/cms/database/migrations/2018_11_01_000001_Db_Cms_Theme_Templates.php
  modules/cms/lang/en/lang.php
  modules/system/ServiceProvider.php
  modules/system/console/ThemeSync.php
Labels: Priority: Medium, Status: In Progress, Type: Enhancement

#4358 Use temporaryUrls for protected files if the storage driver supports them
  config/cms.php
  modules/backend/controllers/Files.php
  modules/system/models/File.php
Labels: Status: Review Needed, Testing Needed, Type: Enhancement

#4356 Restore FroalaEditor extendability
  modules/backend/formwidgets/richeditor/assets/js/build-plugins-min.js
  modules/backend/formwidgets/richeditor/assets/js/richeditor.js
Labels: Testing Needed, Type: Maintenance

#4355 Apply custom secondary color to Pages list
  modules/backend/models/brandsetting/custom.less
Labels: Status: Response Needed, Type: Maintenance

#4362 This fixes the issue with menus not being displayed in pages plugin
  modules/cms/classes/Meta.php
Labels: Type: Bug, Type: Maintenance

#4374 Fix empty menu item counter
  modules/backend/layouts/_mainmenu.htm
Labels: Status: Completed, Type: Maintenance

#4360 Store limited list widget configuration in user preferences
  modules/backend/traits/PreferenceMaker.php
  modules/backend/widgets/Lists.php
  modules/backend/widgets/lists/partials/_setup_form.htm
Labels: Status: Completed, Type: Enhancement

#4240 Update path to video-poster.png
  modules/backend/widgets/mediamanager/partials/_item-sidebar-preview.htm
Labels: Status: Completed, Type: Maintenance

#3964 added tests for optional wildcard parameters
  tests/fixtures/themes/test/pages/blog-category.htm
  tests/unit/cms/classes/CmsObjectQueryTest.php
  tests/unit/cms/classes/RouterTest.php
Labels: Status: Pending, Type: Maintenance

#4378 fixed test hard coded theme url
  tests/unit/cms/classes/ControllerTest.php
Labels: Status: Review Needed, Type: Maintenance

#4364 Hide popup loading indicator if an error/flash is thrown from an AJAX handler
  modules/system/assets/ui/js/popup.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Completed, Type: Maintenance

#4353 Fix: use default options for private thumbs
  modules/system/models/File.php
Labels: Status: Completed, Type: Maintenance

#4285 Add new Performance API's to October CMS
  modules/backend/layouts/_head.htm
  modules/backend/layouts/auth.htm
  modules/cms/twig/FrameworkNode.php
Labels: Status: Response Needed, Type: Enhancement

#4349 Add taglist preview mode
  modules/backend/formwidgets/taglist/partials/_taglist.htm
  modules/system/assets/ui/less/select.less
  modules/system/assets/ui/less/taglist.less
  modules/system/assets/ui/storm.css
  modules/system/assets/ui/storm.less
Labels: Status: Completed, Type: Maintenance

#4391 Fix FormData initialization in framework.js
  modules/system/assets/js/framework-min.js
  modules/system/assets/js/framework.combined-min.js
  modules/system/assets/js/framework.js
Labels: Status: Response Needed, Type: Maintenance

#4390 Fix the S3 temporaryUrl generating issue
  modules/backend/controllers/Files.php
Labels: Status: Completed, Type: Bug

#4394 Improve Travis CI build process
  .travis.yml
  composer.json
  modules/backend/controllers/Index.php
  phpcs.xml
  phpunit.xml
Labels: Status: Review Needed, Type: Maintenance

#4408 Fix Travis CI file scope
  .travis.yml
  modules/backend/models/ExportModel.php
Labels: Type: Maintenance

#4385 Block off SW running in backend and reduce lookups
  config/cms.php
  modules/backend/assets/js/auth/uninstall-sw.js
  modules/backend/controllers/Auth.php
  modules/backend/layouts/_head.htm
  modules/backend/layouts/auth.htm
Labels: Testing Needed, Type: Maintenance

#4415 Missing translations pt-br in validation
  modules/system/lang/pt-br/validation.php
Labels: Status: Completed, Type: Maintenance

#4424 Clean up index functionality in Repeater widget
  modules/backend/formwidgets/Repeater.php
Labels: Status: Completed, Type: Maintenance
