Repository octobercms/october, pull requests merged in 2019-07, with the labels that each got.

#4414 Resolve AJAX Select2 Issues
  modules/system/assets/ui/docs/select.md
  modules/system/assets/ui/js/select.js
  modules/system/assets/ui/storm-min.js
Labels: Type: Maintenance

#4427 Add additional test cases for PluginManager
  phpcs.xml
  tests/fixtures/plugins/dependencytest/dependency/Plugin.php
  tests/fixtures/plugins/dependencytest/dependency/updates/version.yaml
  tests/fixtures/plugins/dependencytest/found/Plugin.php
  tests/fixtures/plugins/dependencytest/found/updates/version.yaml
  tests/fixtures/plugins/dependencytest/notfound/Plugin.php
  tests/fixtures/plugins/dependencytest/notfound/updates/version.yaml
  tests/fixtures/plugins/dependencytest/wrongcase/Plugin.php
  tests/fixtures/plugins/dependencytest/wrongcase/updates/version.yaml
  tests/unit/system/classes/PluginManagerTest.php
Labels: Status: Review Needed, Type: Maintenance

#4337 Make plugin dependency checks case-insensitive
  modules/system/classes/PluginManager.php
  tests/unit/system/classes/PluginManagerTest.php
Labels: Status: Completed, Type: Maintenance

#4433 Fix backend same filename check bug
  modules/cms/widgets/templatelist/partials/_items.htm
Labels: Status: Completed, Type: Bug

#4395 Accessibility enhancement for code editor icons
  modules/backend/formwidgets/codeeditor/assets/css/codeeditor.css
  modules/backend/formwidgets/codeeditor/assets/less/codeeditor.less
Labels: Type: Maintenance

#4447 update cms zh-cn lang.php file
  modules/backend/lang/zh-cn/lang.php
  modules/cms/lang/zh-cn/lang.php
  modules/system/lang/zh-cn/lang.php
Labels: Status: Completed, Type: Maintenance

#4448 Missing Spanish Translations
  modules/backend/lang/es/lang.php
Labels: Status: Completed, Type: Maintenance

#4450 Many translations to pt-br
  modules/backend/lang/pt-br/lang.php
  modules/cms/lang/pt-br/lang.php
  modules/system/assets/js/lang/lang.fi.js
  modules/system/assets/js/lang/lang.nl.js
  modules/system/assets/js/lang/lang.pt-br.js
  modules/system/lang/pt-br/client.php
  modules/system/lang/pt-br/lang.php
Labels: Status: Completed, Type: Maintenance

#4455 update lang.php (russian)
  modules/system/lang/ru/lang.php
Labels: Status: Completed, Type: Maintenance

#4457 Fix layout of color picker for no color selected
  modules/backend/ServiceProvider.php
  modules/backend/formwidgets/colorpicker/assets/css/colorpicker.css
  modules/backend/formwidgets/colorpicker/assets/js/colorpicker.js
  modules/backend/formwidgets/colorpicker/assets/less/colorpicker.less
Labels: Status: Completed, Type: Maintenance

#4401 Add Tab WAI-ARIA Support
  modules/backend/assets/css/october.css
  modules/backend/assets/js/backend.js
  modules/backend/assets/js/october.tabformexpandcontrols.js
  modules/backend/assets/less/layout/mainmenu.less
  modules/backend/lang/ar/lang.php
  modules/backend/lang/be/lang.php
  modules/backend/lang/bg/lang.php
  modules/backend/lang/ca/lang.php
  modules/backend/lang/cs/lang.php
  modules/backend/lang/da/lang.php
  modules/backend/lang/de/lang.php
  modules/backend/lang/el/lang.php
  modules/backend/lang/en/lang.php
  modules/backend/lang/es-ar/lang.php
  modules/backend/lang/es/lang.php
  modules/backend/lang/et/lang.php
  modules/backend/lang/fa/lang.php
  modules/backend/lang/fi/lang.php
  modules/backend/lang/fr/lang.php
  modules/backend/lang/hu/lang.php
  modules/backend/lang/id/lang.php
  modules/backend/lang/it/lang.php
  modules/backend/lang/ja/lang.php
  modules/backend/lang/kr/lang.php
  modules/backend/lang/lt/lang.php
  modules/backend/lang/lv/lang.php
  modules/backend/lang/nb-no/lang.php
  modules/backend/lang/nl/lang.php
  modules/backend/lang/pl/lang.php
  modules/backend/lang/pt-br/lang.php
  modules/backend/lang/pt-pt/lang.php
  modules/backend/lang/ro/lang.php
  modules/backend/lang/ru/lang.php
  modules/backend/lang/sk/lang.php
  modules/backend/lang/sv/lang.php
  modules/backend/lang/tr/lang.php
  modules/backend/lang/uk/lang.php
  modules/backend/lang/vn/lang.php
  modules/backend/lang/zh-cn/lang.php
  modules/backend/lang/zh-tw/lang.php
  modules/backend/layouts/_footer.htm
  modules/backend/layouts/_mainmenu.htm
  modules/backend/layouts/_sidenav.htm
  modules/backend/layouts/default.htm
  modules/backend/widgets/form/partials/_form_tabs.htm
  modules/system/assets/ui/docs/tab.md
  modules/system/assets/ui/storm-min.js
  modules/system/assets/ui/storm.js
  modules/system/assets/ui/vendor/focus-visible/focus-visible.js
  modules/system/assets/ui/vendor/keyboardevent-key-polyfill/index.js
Labels: Status: Completed, Type: Enhancement

#4445 Fix text filter scope
  modules/backend/widgets/Filter.php
  modules/backend/widgets/filter/partials/_scope_text.htm
Labels: Status: Completed, Type: Maintenance

#4460 Fix the Debugger Widget
  modules/cms/twig/DebugExtension.php
Labels: Status: Completed, Type: Maintenance

#4077 Add "maxFilesize" param to backend form widget "fileupload"
  .github/FUNDING.yml
  modules/backend/formwidgets/FileUpload.php
  modules/backend/formwidgets/fileupload/assets/js/fileupload.js
  modules/backend/formwidgets/fileupload/partials/_file_multi.htm
  modules/backend/formwidgets/fileupload/partials/_file_single.htm
  modules/backend/formwidgets/fileupload/partials/_image_multi.htm
  modules/backend/formwidgets/fileupload/partials/_image_single.htm
Labels: Status: Completed, Type: Enhancement

#4462 hidden link access logs in Welcome reportwidget if not has permission
  modules/backend/reportwidgets/welcome/partials/_widget.htm
Labels: Status: Completed, Type: Maintenance

#4266 Add option to disable UpdateManager after backend login
  config/cms.php
  modules/backend/controllers/Auth.php
Labels: Type: Maintenance

#4464 Add support for tab icons in theme customization
  modules/cms/controllers/ThemeOptions.php
Labels: Status: Completed, Type: Maintenance

#4470 Remove alert to prevent showing same popup twice
  modules/cms/assets/js/october.cmspage.js
Labels: Status: Completed, Type: Maintenance

#4472 Add Thai translation
  modules/backend/lang/th/lang.php
  modules/backend/models/Preference.php
  modules/cms/lang/th/lang.php
  modules/system/assets/js/lang/lang.th.js
  modules/system/lang/en/lang.php
  modules/system/lang/th/client.php
  modules/system/lang/th/lang.php
Labels: Status: Completed, Type: Enhancement

#4485 Fix Rich Editor to fill the full height of the container textarea
  modules/backend/formwidgets/richeditor/assets/css/richeditor.css
  modules/backend/formwidgets/richeditor/assets/less/richeditor.less
Labels: Status: Completed, Type: Maintenance
