Repository octobercms/october, pull requests merged in 2019-02, with the labels that each got.

#4102 Allow datatables to work within a repeater
  modules/backend/formwidgets/DataTable.php
  modules/backend/formwidgets/Repeater.php
  modules/backend/formwidgets/repeater/assets/js/repeater.js
  modules/backend/widgets/Table.php
Labels: Status: Completed, Type: Enhancement

#4110 Fix inconsistency with filesize display in file upload widget
  modules/backend/formwidgets/fileupload/assets/js/fileupload.js
Labels: Status: Completed, Type: Maintenance

#4111 Set the datetime value with time 00:00:00 when using the date mode
  modules/backend/formwidgets/DatePicker.php
  modules/backend/formwidgets/datepicker/partials/_datepicker.htm
  modules/system/assets/ui/js/datepicker.js
Labels: Status: Completed, Type: Maintenance

#4121 Improved Translations for Turkish Language
  modules/backend/lang/tr/lang.php
  modules/cms/lang/tr/lang.php
  modules/system/lang/tr/client.php
  modules/system/lang/tr/lang.php
  modules/system/lang/tr/validation.php
Labels: Status: Review Needed, Type: Maintenance

#4123 Fixed link to Contributing Guidelines
  README.md
Labels: Type: Maintenance

#4130 Quick grammar fix to File Upload widget
  modules/backend/formwidgets/fileupload/assets/js/fileupload.js
Labels: Type: Maintenance

#4129 fixes enable defaults on repeater
  modules/backend/formwidgets/Repeater.php
Labels: Type: Maintenance

#4124 Reimplemented infinite loading bar with transforms instead of widths
  modules/system/assets/css/framework.extras.css
  modules/system/assets/less/framework.extras.less
Labels: Status: Completed, Type: Maintenance

#4140 Add popup-allow-focus for the second range input
  modules/system/assets/ui/js/filter.dates.js
Labels: Status: Completed, Type: Maintenance

#4083 Allow multiline changelog messages on plugin page and preserve correct order of updates
  modules/system/classes/VersionManager.php
  modules/system/controllers/Updates.php
  modules/system/controllers/updates/details.htm
  tests/TestCase.php
  tests/fixtures/plugins/october/tester/updates/create_blog_settings_table.php
  tests/fixtures/plugins/october/tester/updates/create_comments_table.php
  tests/fixtures/plugins/october/tester/updates/version.yaml
  tests/unit/backend/models/ExportModelTest.php
  tests/unit/backend/models/ImportModelTest.php
  tests/unit/cms/classes/CmsExceptionTest.php
  tests/unit/system/classes/CombineAssetsTest.php
  tests/unit/system/classes/MarkupManagerTest.php
  tests/unit/system/classes/PluginManagerTest.php
  tests/unit/system/classes/UpdatesControllerTest.php
  tests/unit/system/classes/VersionManagerTest.php
  tests/unit/system/traits/AssetMakerTest.php
Labels: Status: Review Needed, Type: Enhancement

#4148 Add backend.list.extendRecords event for export
  modules/backend/behaviors/ImportExportController.php
Labels: Status: Completed, Type: Maintenance

#4157 Update french translations
  modules/backend/lang/fr/lang.php
Labels: Type: Maintenance

#4127 I added to the CLI this commands: plugin:list, plugin:disable & plugin:enable.
  .gitignore
  modules/system/ServiceProvider.php
  modules/system/console/PluginDisable.php
  modules/system/console/PluginEnable.php
  modules/system/console/PluginList.php
Labels: Status: Review Needed, Type: Enhancement

#4156 Defer plugin installs from cli advanced step until October is installed
  modules/system/console/OctoberInstall.php
Labels: Status: Completed, Type: Maintenance

#4163 Update Arabic language
  modules/backend/lang/ar/lang.php
Labels: Type: Maintenance

#4106 Allow controller middleware in backend controllers
  modules/backend/classes/BackendController.php
  modules/backend/classes/Controller.php
Labels: Status: Review Needed, Type: Maintenance

#4142 Return 500 when asset exception caught
  modules/system/classes/SystemController.php
Labels: Status: Response Needed, Type: Maintenance

#4170 Add Closure to Backend\Classes\Controller
  modules/backend/classes/Controller.php
Labels: Type: Maintenance

#4171 Use 1px for 'min-size' layout rows to fix Firefox spacing issue
  modules/backend/assets/css/october.css
  modules/backend/assets/less/layout/layout.less
Labels: Type: Maintenance
