Repository octobercms/october, pull requests merged in 2019-09, with the labels that each got.

#4583 Add translations for plugin author to system module
  modules/system/controllers/updates/_install_plugins.htm
  modules/system/lang/ca/lang.php
  modules/system/lang/cs/lang.php
  modules/system/lang/en/lang.php
  modules/system/lang/et/lang.php
  modules/system/lang/fa/lang.php
  modules/system/lang/fi/lang.php
  modules/system/lang/hu/lang.php
  modules/system/lang/kr/lang.php
  modules/system/lang/nl/lang.php
  modules/system/lang/pt-br/lang.php
  modules/system/lang/ru/lang.php
  modules/system/lang/sk/lang.php
  modules/system/lang/th/lang.php
  modules/system/lang/tr/lang.php
  modules/system/lang/uk/lang.php
  modules/system/lang/vn/lang.php
  modules/system/lang/zh-cn/lang.php
Labels: Status: Completed, Type: Maintenance

#4546 Make the Code editor fullscreen button easier to see
  modules/backend/formwidgets/codeeditor/assets/css/codeeditor.css
  modules/backend/formwidgets/codeeditor/assets/less/codeeditor.less
Labels: Status: Completed, Type: Maintenance

#4594 Remove the IE5 - IE7 Holly Hack support
  modules/backend/formwidgets/colorpicker/assets/css/colorpicker.css
  modules/backend/widgets/reportcontainer/assets/css/reportcontainer.css
  modules/cms/assets/css/october.components.css
  modules/cms/widgets/assetlist/assets/css/assetlist.css
  modules/system/assets/ui/less/icon.mixins.less
  themes/demo/assets/vendor/font-awesome/css/font-awesome.css
  themes/demo/assets/vendor/font-awesome/less/mixins.less
Labels: Status: Completed, Type: Maintenance

#4577 Add documentation for testing pull requests
  .github/CONTRIBUTING.md
  README.md
Labels: Status: Completed, Type: Maintenance

#4598 Fail CSRF token checks if the session expires.
  modules/backend/classes/Controller.php
  modules/cms/classes/Controller.php
Labels: Status: Completed, Type: Maintenance

#4596 Correction of the link for contribute
  README.md
Labels: Status: Completed, Type: Maintenance

#4608 Ignore IDE helper file
  .gitignore
Labels: Status: Completed, Type: Maintenance

#4612 $filePath -> &$filePath in media.file.upload event
  modules/backend/widgets/MediaManager.php
Labels: Status: Completed, Type: Maintenance

#4616 $filePath in the media.file.upload e. by reference
  modules/backend/widgets/MediaManager.php
Labels: Status: Completed, Type: Maintenance

#4517 Replace use of parseJSON with JSON.parse
  modules/backend/widgets/reportcontainer/assets/js/reportcontainer.js
  modules/cms/assets/js/october.cmspage.js
  modules/system/assets/ui/js/inspector.datainteraction.js
  modules/system/assets/ui/js/inspector.editor.objectlist.js
  modules/system/assets/ui/js/inspector.wrapper.base.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Completed, Type: Maintenance

#4428 Fix error when $user is null
  modules/system/classes/SettingsManager.php
Labels: Status: Review Needed, Type: Maintenance

#4629 Show table scrolling a bit clearer - ux fix
  modules/system/assets/ui/less/list.less
  modules/system/assets/ui/storm.css
Labels: Type: Maintenance

#4522 New method removePermission() for AuthManager
  modules/backend/classes/AuthManager.php
  tests/unit/backend/classes/AuthManagerTest.php
Labels: Status: Completed, Type: Maintenance

#4633 Add GitHub Actions workflows
  .github/workflows/code-quality-pr.yaml
  .github/workflows/code-quality-push.yaml
  .github/workflows/tests.yml
  .github/workflows/wrong-branch-notification.yaml
  .travis.yml
Labels: Status: Completed, Type: Maintenance

#4634 Update lang.php
  modules/backend/lang/pl/lang.php
Labels: Status: Completed, Type: Maintenance

#4576 Initial unit tests for front-end framework
  .babelrc
  .github/workflows/frontend-tests.yaml
  .gitignore
  .jshintrc
  modules/system/assets/js/framework-min.js
  modules/system/assets/js/framework.combined-min.js
  modules/system/assets/js/framework.js
  package.json
  tests/js/cases/system/framework.test.js
  tests/js/helpers/fakeDom.js
Labels: Status: Completed, Type: Enhancement

#4151 Added SparkPost mail setting
  config/services.php
  modules/system/lang/en/lang.php
  modules/system/models/MailSetting.php
  modules/system/models/mailsetting/fields.yaml
Labels: Status: Completed, Type: Enhancement

#4526 Use parseFile for caching and parsing
  modules/cms/classes/Theme.php
  modules/system/traits/ConfigMaker.php
Labels: Status: Completed, Type: Enhancement

#3220 Optimize theme recognition
  modules/cms/classes/Theme.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#4635 update zh-cn translations of backend
  modules/backend/lang/zh-cn/lang.php
  modules/cms/lang/zh-cn/lang.php
  modules/system/lang/zh-cn/lang.php
Labels: Status: Completed, Type: Maintenance

#4640 Update delete buttons in user controllers
  modules/backend/controllers/usergroups/update.htm
  modules/backend/controllers/userroles/update.htm
Labels: Status: Completed, Type: Maintenance

#4644 Update mustache.js from 2.0.0 to 2.3.2
  modules/system/assets/ui/vendor/mustache/mustache.js
Labels: Priority: Low, Type: Maintenance

#4646 Add auto-archive action
  .github/workflows/archive.yml
Labels: Status: Completed, Type: Maintenance
