Repository octobercms/october, pull requests merged in 2019-05, with the labels that each got.

#4177 Finnish language update
  modules/backend/lang/fi/lang.php
  modules/cms/lang/fi/lang.php
  modules/system/lang/fi/client.php
  modules/system/lang/fi/lang.php
  modules/system/lang/fi/validation.php
Labels: Status: Revision Needed, Type: Maintenance

#4241 Add support for filters on the RelationController
  modules/backend/behaviors/RelationController.php
  modules/backend/behaviors/relationcontroller/partials/_manage_list.htm
  modules/backend/behaviors/relationcontroller/partials/_view.htm
  modules/backend/widgets/Filter.php
Labels: Status: Completed, Type: Enhancement

#4311 Add "onUpload" AJAX handler to FileUpload widget
  modules/backend/formwidgets/FileUpload.php
  modules/backend/formwidgets/fileupload/assets/js/fileupload.js
  modules/backend/formwidgets/fileupload/partials/_file_multi.htm
  modules/backend/formwidgets/fileupload/partials/_file_single.htm
  modules/backend/formwidgets/fileupload/partials/_image_multi.htm
  modules/backend/formwidgets/fileupload/partials/_image_single.htm
Labels: Status: Completed, Type: Maintenance

#4321 Dutch language update
  modules/backend/lang/nl/lang.php
  modules/system/lang/nl/client.php
  modules/system/lang/nl/lang.php
Labels: Type: Maintenance

#4323 Disable in-memory cache repository when running in CLI by default
  config/cache.php
Labels: Status: Completed, Type: Enhancement

#4305 Fix media manager access
  modules/backend/formwidgets/MarkdownEditor.php
  modules/backend/formwidgets/RichEditor.php
  modules/backend/formwidgets/markdowneditor/assets/js/markdowneditor.js
  modules/backend/formwidgets/markdowneditor/partials/_markdowneditor.htm
  modules/backend/formwidgets/richeditor/assets/js/build-plugins-min.js
  modules/backend/formwidgets/richeditor/assets/js/richeditor.js
  modules/backend/formwidgets/richeditor/partials/_richeditor.htm
Labels: Testing Needed, Type: Maintenance

#4334 Do not reset groupMap indexes
  modules/backend/formwidgets/Repeater.php
Labels: Priority: High, Status: Completed, Type: Bug

#4331 Add check to make sure event result is an array in Form widget
  modules/backend/widgets/Form.php
Labels: Status: Completed, Type: Maintenance

#4011 Media Manager with SVG preview
  modules/backend/widgets/MediaManager.php
  modules/backend/widgets/mediamanager/assets/css/mediamanager.css
  modules/backend/widgets/mediamanager/assets/less/mediamanager.less
Labels: Status: Review Needed, Type: Enhancement

#4348 Default to full width dashboard widgets
  modules/backend/widgets/reportcontainer/partials/_new_widget_popup.htm
Labels: Type: Maintenance
