Repository octobercms/october, pull requests merged in 2020-04, with the labels that each got.

#5017 Add usingSource method to active datasource to properly sync to speci…
  modules/cms/classes/AutoDatasource.php
  modules/system/console/ThemeSync.php
Labels: Status: Completed, Type: Maintenance

#4838 PluginManager normalizations
  tests/unit/system/classes/PluginManagerTest.php
Labels: Status: Review Needed, Type: Maintenance

#5022 improve code readability for exists method
  modules/system/classes/PluginManager.php
  tests/unit/system/classes/PluginManagerTest.php
Labels: Status: Completed, Type: Maintenance

#5023 Improve code
  modules/system/classes/PluginManager.php
Labels: Status: Completed, Type: Maintenance

#4997 filterFields triggered with Add or Change with pivot
  modules/backend/behaviors/relationcontroller/partials/_pivot_form.htm
Labels: Status: Completed, Type: Maintenance

#4811 Remove JS layout calculations of the backend navbar by using flexbox
  modules/backend/assets/css/october.css
  modules/backend/assets/js/october-min.js
  modules/backend/assets/js/october.navbar.js
  modules/backend/assets/less/layout/mainmenu.less
  modules/backend/layouts/_mainmenu.htm
Labels: Status: Completed, Type: Maintenance

#4770 1. Fix paths to plugins and themes for update manager
  modules/system/classes/UpdateManager.php
Labels: Status: Completed, Type: Maintenance

#4700 Preset buttons for editor toolbar settings
  modules/backend/formwidgets/richeditor/assets/css/richeditor.css
  modules/backend/formwidgets/richeditor/assets/less/richeditor.less
  modules/backend/lang/ca/lang.php
  modules/backend/lang/cs/lang.php
  modules/backend/lang/de/lang.php
  modules/backend/lang/en/lang.php
  modules/backend/lang/fa/lang.php
  modules/backend/lang/fi/lang.php
  modules/backend/lang/fr/lang.php
  modules/backend/lang/hu/lang.php
  modules/backend/lang/nl/lang.php
  modules/backend/lang/pl/lang.php
  modules/backend/lang/pt-br/lang.php
  modules/backend/lang/pt-pt/lang.php
  modules/backend/lang/ru/lang.php
  modules/backend/lang/sk/lang.php
  modules/backend/lang/th/lang.php
  modules/backend/lang/tr/lang.php
  modules/backend/lang/uk/lang.php
  modules/backend/lang/vn/lang.php
  modules/backend/lang/zh-cn/lang.php
  modules/backend/models/EditorSetting.php
  modules/backend/models/editorsetting/_toolbar_presets.htm
  modules/backend/models/editorsetting/fields.yaml
Labels: Status: Completed, Type: Enhancement

#5026 Simplify Media Library upload logic
  modules/backend/formwidgets/RichEditor.php
  modules/backend/formwidgets/richeditor/assets/css/richeditor.css
  modules/backend/formwidgets/richeditor/assets/js/build-plugins-min.js
  modules/backend/formwidgets/richeditor/assets/js/richeditor.js
  modules/backend/formwidgets/richeditor/assets/less/richeditor.less
  modules/backend/formwidgets/richeditor/partials/_richeditor.htm
  modules/backend/traits/UploadableWidget.php
  modules/backend/widgets/MediaManager.php
  modules/backend/widgets/mediamanager/assets/js/mediamanager-browser-min.js
  modules/backend/widgets/mediamanager/assets/js/mediamanager.js
  modules/backend/widgets/mediamanager/partials/_body.htm
  modules/backend/widgets/mediamanager/partials/_toolbar.htm
Labels: Status: Completed, Type: Maintenance

#4539 Soft Component Support
  modules/cms/assets/css/october.components.css
  modules/cms/assets/js/october.cmspage.js
  modules/cms/assets/less/october.components.less
  modules/cms/classes/ComponentHelpers.php
  modules/cms/classes/ComponentManager.php
  modules/cms/classes/Controller.php
  modules/cms/components/SoftComponent.php
  modules/cms/controllers/Index.php
  modules/cms/formwidgets/Components.php
  modules/cms/lang/en/lang.php
  tests/fixtures/themes/test/pages/no-soft-component-class.htm
  tests/fixtures/themes/test/pages/with-soft-component-class-alias.htm
  tests/fixtures/themes/test/pages/with-soft-component-class.htm
  tests/unit/cms/classes/CmsObjectQueryTest.php
  tests/unit/cms/classes/ControllerTest.php
Labels: Status: Completed, Type: Enhancement

#5027 Improved Hungarian translation
  modules/backend/lang/hu/lang.php
  modules/system/lang/hu/client.php
Labels: Status: Completed, Type: Maintenance

#4754 Linkable form tabs
  modules/backend/classes/FormTabs.php
  modules/backend/widgets/form/partials/_form_tabs.htm
  modules/system/assets/ui/js/tab.js
Labels: Status: Completed, Type: Enhancement

#4966 Add option to ignore timestamps for date range filters
  modules/backend/widgets/Filter.php
  modules/backend/widgets/filter/partials/_scope_daterange.htm
  modules/system/assets/ui/js/filter.dates.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Completed, Type: Maintenance

#5028 Slovenian language update
  modules/backend/lang/sl/lang.php
  modules/cms/lang/sl/lang.php
  modules/system/lang/sl/client.php
  modules/system/lang/sl/lang.php
Labels: Status: Completed, Type: Maintenance

#5032 Unsuspend a backend user from user update screen.
  modules/backend/controllers/Users.php
  modules/backend/controllers/users/_btn_unsuspend.htm
  modules/backend/lang/en/lang.php
  modules/backend/models/User.php
  modules/backend/models/user/fields.yaml
Labels: Status: Completed, Type: Enhancement

#5035 Reset outline to default - roll back #4895
  modules/backend/assets/css/october.css
  modules/backend/assets/less/layout/mainmenu.less
  modules/system/assets/css/styles.css
  modules/system/assets/ui/less/global.mixins.utility.css
  modules/system/assets/ui/less/global.mixins.utility.less
  modules/system/assets/ui/less/site.normalize.less
  modules/system/assets/ui/storm.css
Labels: Status: Review Needed, Type: Maintenance

#4804 Validate backend forms client-side
  modules/backend/classes/FormField.php
  modules/system/assets/js/framework.js
Labels: Status: Completed, Type: Maintenance

#4389 New command plugin:rollback
  modules/system/ServiceProvider.php
  modules/system/classes/UpdateManager.php
  modules/system/classes/VersionManager.php
  modules/system/console/PluginRollback.php
  modules/system/lang/en/lang.php
  modules/system/lang/pt-br/lang.php
Labels: Status: Completed, Type: Enhancement

#5038 Allow translations of default column values
  modules/backend/widgets/Lists.php
Labels: Status: Completed, Type: Maintenance

#5040 Added Serbian localization.
  modules/backend/lang/rs/lang.php
  modules/backend/models/Preference.php
  modules/cms/lang/rs/lang.php
  modules/system/lang/ar/lang.php
  modules/system/lang/en/lang.php
  modules/system/lang/et/lang.php
  modules/system/lang/fa/lang.php
  modules/system/lang/fi/lang.php
  modules/system/lang/lt/lang.php
  modules/system/lang/nl/lang.php
  modules/system/lang/pt-pt/lang.php
  modules/system/lang/rs/client.php
  modules/system/lang/rs/lang.php
  modules/system/lang/rs/validation.php
  modules/system/lang/sk/lang.php
  modules/system/lang/sl/lang.php
  modules/system/lang/tr/lang.php
  modules/system/lang/vn/lang.php
Labels: Status: Completed, Type: Enhancement

#5042 Allow blob files naming in AJAX request
  modules/system/assets/js/framework-min.js
  modules/system/assets/js/framework.combined-min.js
  modules/system/assets/js/framework.js
Labels: Status: Completed, Type: Enhancement

#5047 Update check for '.git' when using 'php artisan october:util git pull'
  modules/system/console/OctoberUtil.php
Labels: Status: Completed, Type: Maintenance

#5048 Updated Russian translation
  modules/system/lang/ru/lang.php
Labels: Status: Completed, Type: Maintenance

#5039 Don't persist failed search terms
  modules/backend/widgets/Search.php
Labels: Status: Completed, Type: Maintenance
