Repository octobercms/october, pull requests merged in 2020-03, with the labels that each got.

#4929 Modify menu structure to objects
  modules/backend/classes/MainMenuItem.php
  modules/backend/classes/NavigationManager.php
  modules/backend/classes/SideMenuItem.php
Labels: Status: Review Needed, Type: Enhancement

#4908 Updated getParameter method
  modules/cms/classes/Router.php
Labels: Status: Completed, Type: Maintenance

#4961 add translation for 'Insert File' [DE]
  modules/backend/formwidgets/richeditor/assets/vendor/froala/js/languages/de.js
Labels: Status: Completed, Type: Maintenance

#4967 Auto-detect correct postback handler for datatable widget.
  modules/backend/widgets/Table.php
  modules/backend/widgets/table/assets/js/build-min.js
  modules/backend/widgets/table/assets/js/table.js
  modules/backend/widgets/table/partials/_table.htm
Labels: Status: Completed, Type: Maintenance

#4974 Add configuration for throttling authentication attemptsAuth config
  config/auth.php
  modules/backend/classes/AuthManager.php
  modules/backend/models/UserThrottle.php
Labels: Status: Completed, Type: Enhancement

#4977 Get correct model when not using ID for "keyFrom" in Record Finder
  modules/backend/formwidgets/RecordFinder.php
Labels: Status: Completed, Type: Maintenance

#4978 Allow dot-notation for specifying external parameters for a component
  modules/cms/classes/Controller.php
Labels: Status: Completed, Type: Maintenance

#4972 Fix docblocks and imports in FormController behaviour.
  modules/backend/behaviors/FormController.php
Labels: Status: Completed, Type: Maintenance

#4987 Add GitHub Action for comment commands
  .github/workflows/commander.yml
Labels: Status: In Progress, Type: Enhancement

#4992 Add adaptive popup size options to Storm UI docs
  modules/system/assets/ui/docs/popup.md
Labels: Status: Completed, Type: Maintenance

#4954 Add formGetRedirectUrl method. Fixes #4946
  modules/backend/behaviors/FormController.php
Labels: Status: Completed, Type: Maintenance

#4989 Fix docbocks ListController behaviour.
  modules/backend/behaviors/ListController.php
  modules/backend/traits/WidgetMaker.php
Labels: Status: Review Needed, Type: Maintenance

#4998 Replace Illuminate Dumper with Symfony Dumper
  modules/cms/twig/DebugExtension.php
Labels: Status: Completed, Type: Maintenance

#5001 Add support for html attributes to the codeditor formwidget
  modules/backend/formwidgets/codeeditor/partials/_codeeditor.htm
Labels: Status: Completed, Type: Maintenance

#4986 Allow quotes to be correctly handled by october:env
  modules/system/console/OctoberEnv.php
  tests/fixtures/config/app.php
  tests/fixtures/config/cache.php
  tests/fixtures/config/cms.php
  tests/fixtures/config/database.php
  tests/fixtures/config/mail.php
  tests/fixtures/config/queue.php
  tests/fixtures/config/session.php
  tests/unit/system/console/OctoberEnvTest.php
Labels: Status: Completed, Type: Maintenance

#4873 Add UTF-8 BOM when exporting with the useList option
  modules/backend/behaviors/ImportExportController.php
Labels: Status: Completed, Type: Maintenance

#5003 Modify password field to support placeholder attribute
  modules/backend/widgets/form/partials/_field_password.htm
Labels: Status: Completed, Type: Maintenance

#5008 Change default https redirect from 302 to 301
  .htaccess
Labels: Status: Completed, Type: Maintenance

#5005 Russian language updated
  modules/backend/lang/en/lang.php
  modules/backend/lang/ru/lang.php
Labels: Status: Completed, Type: Maintenance

#4444 Relation Manager Customisation Improvements
  modules/backend/behaviors/RelationController.php
  modules/backend/behaviors/relationcontroller/partials/_button_add.htm
  modules/backend/behaviors/relationcontroller/partials/_button_create.htm
  modules/backend/behaviors/relationcontroller/partials/_button_delete.htm
  modules/backend/behaviors/relationcontroller/partials/_button_link.htm
  modules/backend/behaviors/relationcontroller/partials/_button_remove.htm
  modules/backend/behaviors/relationcontroller/partials/_button_unlink.htm
  modules/backend/behaviors/relationcontroller/partials/_button_update.htm
  modules/backend/behaviors/relationcontroller/partials/_toolbar.htm
Labels: Status: Completed, Type: Enhancement

#5012 Add attributes support to fileupload widget
  modules/backend/formwidgets/fileupload/partials/_file_multi.htm
  modules/backend/formwidgets/fileupload/partials/_file_single.htm
  modules/backend/formwidgets/fileupload/partials/_image_multi.htm
  modules/backend/formwidgets/fileupload/partials/_image_single.htm
Labels: Status: Completed, Type: Maintenance

#4698 Fix: Not reflecting "defaultMask" when uploading file@CMS
  modules/cms/widgets/AssetList.php
Labels: Status: Completed, Type: Maintenance

#5004 Markdown formwidget improvements
  modules/backend/ServiceProvider.php
  modules/backend/formwidgets/MarkdownEditor.php
  modules/backend/formwidgets/markdowneditor/assets/css/markdowneditor.css
  modules/backend/formwidgets/markdowneditor/assets/js/markdowneditor.js
  modules/backend/formwidgets/markdowneditor/assets/less/markdowneditor.less
  modules/backend/formwidgets/markdowneditor/partials/_markdowneditor.htm
Labels: Status: Completed, Type: Maintenance

#5002 Colorpicker improvements
  modules/backend/formwidgets/ColorPicker.php
  modules/backend/formwidgets/colorpicker/assets/css/colorpicker.css
  modules/backend/formwidgets/colorpicker/assets/js/colorpicker.js
  modules/backend/formwidgets/colorpicker/assets/less/colorpicker.less
  modules/backend/formwidgets/colorpicker/partials/_colorpicker.htm
Labels: Status: Completed, Type: Maintenance

#5010 MediaFinder modifications
  modules/backend/formwidgets/MediaFinder.php
  modules/backend/formwidgets/mediafinder/partials/_file_single.htm
  modules/backend/formwidgets/mediafinder/partials/_image_single.htm
  modules/backend/formwidgets/mediafinder/partials/_mediafinder.htm
Labels: Status: Completed, Type: Maintenance

#5011 Richeditor modifications
  modules/backend/formwidgets/richeditor/assets/css/richeditor.css
  modules/backend/formwidgets/richeditor/assets/less/richeditor.less
  modules/backend/formwidgets/richeditor/partials/_richeditor.htm
Labels: Status: Completed, Type: Maintenance

#4661 Add support for non-numeric menu counter values
  modules/backend/classes/MainMenuItem.php
  modules/backend/classes/NavigationManager.php
  modules/backend/classes/SideMenuItem.php
Labels: Status: Completed, Type: Enhancement

#4846 Add an unique identifier to all the filter container popup boxes
  modules/system/assets/ui/js/filter.dates.js
  modules/system/assets/ui/js/filter.js
  modules/system/assets/ui/js/filter.numbers.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Completed, Type: Maintenance

#4904 Load mail templates from view files if not found in the database
  modules/system/models/MailLayout.php
  modules/system/models/MailTemplate.php
Labels: Status: Completed, Type: Maintenance

#4949 Prevent browser caching of checkbox in lists
  modules/backend/widgets/lists/partials/_list_body_checkbox.htm
Labels: Status: Completed, Type: Maintenance

#5015 ImportExportBehavior: Add iconv fallback support for import
  modules/backend/behaviors/importexportcontroller/TranscodeFilter.php
  modules/backend/lang/en/lang.php
  modules/backend/models/ImportModel.php
Labels: Status: Completed, Type: Maintenance

#4822 Fix saving of translations in relation controller by re-using the form widget's model
  modules/backend/behaviors/RelationController.php
Labels: Testing Needed, Type: Bug

#4970 Allows model scope with join in relation form widget
  modules/backend/formwidgets/Relation.php
Labels: Status: Completed, Type: Maintenance
