Repository octobercms/october, pull requests merged in 2020-12, with the labels that each got.

#5375 Update sk.js
  modules/backend/formwidgets/richeditor/assets/vendor/froala/js/languages/sk.js
Labels: Status: Completed, Type: Maintenance

#5374 Fix unit tests
  .github/workflows/tests.yml
  .github/workflows/utilities/library-switcher
  tests/PluginTestCase.php
  tests/TestCase.php
  tests/unit/cms/classes/ThemeTest.php
Labels: Status: In Progress, Type: Maintenance

#5379 Match constructor params docblock
  modules/system/classes/ImageResizer.php
Labels: Status: Completed, Type: Maintenance

#5386 Register plugin after installation
  modules/system/console/PluginInstall.php
Labels: Status: Completed, Type: Maintenance

#5361 use new October\Rain Mail facade
  modules/system/aliases.php
Labels: Status: Blocked, Type: Maintenance

#5367 Ensure that MediaLibrary::listAllDirectories() honors config for paths to ignore
  modules/system/classes/MediaLibrary.php
  tests/unit/system/classes/MediaLibraryTest.php
Labels: Testing Needed, Type: Maintenance

#5398 Fix the placeholder hidden behind the counter in the form widget `number`
  modules/system/assets/css/styles.css
  modules/system/assets/ui/less/site.normalize.less
  modules/system/assets/ui/storm.css
Labels: Status: Completed, Type: Maintenance

#5432 Update CONTRIBUTING to explain about js complier assets
  .github/CONTRIBUTING.md
Labels: Status: Completed, Type: Maintenance

#5433 [typo in comment] L649
  modules/backend/behaviors/FormController.php
Labels: Status: Completed, Type: Maintenance
