Repository octobercms/october, pull requests merged in 2020-11, with the labels that each got.

#5268 Add Sortable Behavior to ReorderController validateModel
  modules/backend/behaviors/ReorderController.php
Labels: Status: Completed, Type: Maintenance

#4960 Backend theme localization
  modules/cms/ServiceProvider.php
  modules/cms/controllers/ThemeOptions.php
Labels: Status: Completed, Type: Enhancement

#5348 fix themes localization namespace
  modules/cms/ServiceProvider.php
Labels: Status: Completed, Type: Maintenance

#5322 Prevent exception when mail templates/layouts are not found
  modules/system/models/MailLayout.php
  modules/system/models/MailPartial.php
  modules/system/models/MailTemplate.php
Labels: Status: Completed, Type: Maintenance

#5344 Add support for defining quick actions in the Backend's main nav
  modules/backend/assets/css/october.css
  modules/backend/assets/less/layout/mainmenu.less
  modules/backend/classes/NavigationManager.php
  modules/backend/classes/QuickActionItem.php
  modules/backend/layouts/_mainmenu.htm
  modules/cms/ServiceProvider.php
  modules/system/classes/PluginBase.php
Labels: Status: Completed, Type: Enhancement

#5349 Move theme localization to the boot process of the CMS Service Provider
  modules/cms/ServiceProvider.php
Labels: Status: Completed, Type: Maintenance

#5355 Component property can be mixed value
  modules/system/traits/PropertyContainer.php
Labels: Status: Completed, Type: Maintenance

#5334 Theme:sync path pattern fix
  modules/system/console/ThemeSync.php
Labels: Status: Completed, Type: Maintenance

#4866 Generate random password for seeded admin account through october:up
  modules/backend/database/seeds/DatabaseSeeder.php
  modules/system/classes/UpdateManager.php
  modules/system/classes/VersionManager.php
  tests/unit/plugins/database/PluginModelTest.php
Labels: Status: In Progress, Status: Review Needed, Type: Enhancement

#5335 Migrate to League\Csv 9.0
  modules/backend/behaviors/ImportExportController.php
Labels: Status: Completed, Type: Maintenance

#5295 Documented richeditor.listTypes & richeditor.getTypeInfo events
  modules/backend/formwidgets/RichEditor.php
Labels: Status: Completed, Type: Maintenance

#5327 Fixes OptionsGeneration Test failing
  tests/unit/backend/widgets/FormTest.php
Labels: Status: Completed, Type: Maintenance
