Repository octobercms/october, pull requests merged in 2020-07, with the labels that each got.

#5052 Document Select2's dynamic option creation
  modules/system/assets/ui/docs/select.md
Labels: Status: Completed, Website / Marketplace / Docs

#5201 Add sensitive field input
  modules/backend/ServiceProvider.php
  modules/backend/formwidgets/Sensitive.php
  modules/backend/formwidgets/sensitive/assets/css/sensitive.css
  modules/backend/formwidgets/sensitive/assets/js/sensitive.js
  modules/backend/formwidgets/sensitive/assets/less/sensitive.less
  modules/backend/formwidgets/sensitive/partials/_sensitive.htm
  modules/system/models/mailsetting/fields.yaml
Labels: Status: Completed, Type: Enhancement

#5206 Fix "use statement with non-compound names has no effect"
  modules/cms/classes/CodeParser.php
Labels: Status: Completed, Type: Maintenance

#5212 Provide an accessor for the form widget of the Settings controller
  modules/system/controllers/Settings.php
Labels: Status: Completed, Type: Maintenance

#5210 Add missing french translations
  modules/cms/lang/fr/lang.php
Labels: Status: Completed, Status: Review Needed

#5053 Clear input after creating tag in taglist
  modules/system/assets/ui/js/select.js
Labels: Type: Bug

#4861 Add Paragraph Formats to Editor Settings
  modules/backend/formwidgets/RichEditor.php
  modules/backend/formwidgets/richeditor/assets/js/richeditor.js
  modules/backend/formwidgets/richeditor/partials/_richeditor.htm
  modules/backend/lang/en/lang.php
  modules/backend/models/EditorSetting.php
  modules/backend/models/editorsetting/fields.yaml
Labels: Status: Completed, Type: Maintenance

#5141 Fix: Filter type "group" does not work when 500+ options are available
  modules/backend/widgets/Filter.php
  modules/system/assets/ui/js/filter.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Completed, Type: Maintenance
