Repository octobercms/october, pull requests merged in 2021-03, with the labels that each got.

#5192 Fix: Rollback plugins
  modules/system/classes/UpdateManager.php
Labels: Status: Response Needed, Type: Maintenance

#5357 PHP 8 compatibility
  .github/workflows/tests.yml
  composer.json
  modules/backend/classes/BackendController.php
  modules/backend/classes/Controller.php
  modules/system/classes/CombineAssets.php
  tests/TestCase.php
  tests/fixtures/plugins/testvendor/goto/Plugin.php
  tests/unit/backend/models/ExportModelTest.php
Labels: Testing Needed, Type: Maintenance

#5506 Permanent Composer 2 compatibility
  composer.json
Labels: Status: Completed, Type: Maintenance, third party

#5507 Update OctoberInstall.php
  modules/system/console/OctoberInstall.php
Labels: Testing Needed, Type: Maintenance

#5520 Radio and checkbox didn't show popup "Please select one of these opti…
  modules/system/assets/ui/storm.css
Labels: Testing Needed, Type: Maintenance

#5112 Unbind event handlers upon destruction of the form widget
  modules/backend/widgets/form/assets/js/october.form.js
Labels: Status: Revision Needed, Testing Needed, Type: Maintenance

#5466 Support saving deferred bindings with pivot data.
  modules/system/database/migrations/2021_01_19_000001_Db_Add_Pivot_Data_To_Deferred_Bindings.php
  tests/fixtures/plugins/database/tester/models/Author.php
  tests/fixtures/plugins/database/tester/models/Category.php
  tests/fixtures/plugins/database/tester/models/Post.php
  tests/fixtures/plugins/database/tester/models/Tag.php
  tests/fixtures/plugins/database/tester/updates/create_posts_table.php
  tests/fixtures/plugins/database/tester/updates/create_tags_table.php
  tests/fixtures/plugins/database/tester/updates/version.yaml
  tests/unit/plugins/database/BelongsToManyModelTest.php
  tests/unit/plugins/database/MorphManyModelTest.php
Labels: Status: In Progress, Type: Enhancement

#5465 implement artisan october:util purge orphans
  modules/system/console/OctoberUtil.php
Labels: Testing Needed, Type: Enhancement

#4920 Allow DI in console command constructor
  modules/system/classes/PluginBase.php
Labels: Testing Needed, Type: Maintenance

#5060 Fix dependency injection for component on cms page
  modules/cms/widgets/ComponentList.php
Labels: Testing Needed, Type: Maintenance

#4683 Support readonly and disabled fields when value is an array
  modules/backend/formwidgets/taglist/partials/_taglist.htm
Labels: Status: Response Needed, Type: Maintenance
